export const bannedExternalPatterns = [
  /\bdraft\b/i,
  /\bfinal candidate\b/i,
  /\bready-to-copy\b/i,
  /\bselected for this open call\b/i,
  /\bselected for\b/i,
  /\bfor this residency\b/i,
  /\bFILE NOT FOUND\b/i,
  /\bgenerated by AI\b/i,
  /\binternal note\b/i,
  /\breview version\b/i,
  /\bapplication package\b/i,
  /\bto be edited\b/i,
  /\bplaceholder\b/i,
  /\bNo website\b/i,
  /\bNo Instagram\b/i,
  /\bNone\b/i,
  /\bN\/A\b/i,
  /\bto be confirmed\b/i,
  /\bTBD\b/i,
  /\bmissing\b/i,
  /\bunknown\b/i
];

export function findBannedExternalTerms(text: string) {
  const hits = new Set<string>();
  for (const pattern of bannedExternalPatterns) {
    const match = text.match(pattern);
    if (match?.[0]) hits.add(match[0]);
  }
  return [...hits];
}

export function sanitizeExternalText(text: string) {
  const internalIssues: string[] = [];
  const cleanedLines = text
    .split(/\r?\n/)
    .filter((line) => {
      const hits = findBannedExternalTerms(line);
      if (hits.length > 0) {
        internalIssues.push(`Removed external-facing line containing internal/placeholder language: ${hits.join(", ")}`);
        return false;
      }
      return true;
    })
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return {
    text: cleanedLines,
    internalIssues,
    remainingBannedTerms: findBannedExternalTerms(cleanedLines)
  };
}

export function assertExternalTextIsClean(label: string, text: string) {
  const hits = findBannedExternalTerms(text);
  if (hits.length > 0) {
    throw new Error(`${label} contains external-forbidden terms: ${hits.join(", ")}`);
  }
}
