import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import type { Opportunity, PortfolioDesignSystem, PortfolioIssueClassification, PortfolioPlan, PortfolioPlanImage, PortfolioPlanPage, PortfolioThemeName, PortfolioVisualGateResult } from "@/types/domain";

const requireFromRenderer = createRequire(import.meta.url);

export type CopiedPortfolioImage = {
  sourcePath: string;
  targetFileName: string;
  width: number;
  height: number;
  format: string;
  sizeBytes: number;
  optimized: boolean;
  tooSmallForFullPage: boolean;
};

type PortfolioRenderInput = {
  externalDir: string;
  internalDir: string;
  opportunity: Opportunity;
  plan: PortfolioPlan;
  copiedImages: CopiedPortfolioImage[];
  webResearchReferences: string[];
  preflightIssues: string[];
  outputBaseName?: string;
};

const forbiddenExternalPattern = /\b(test preview|web preview|browser preview|mock|test pdf|review committee|draft|placeholder|generated by ai|for this open call|selected for|ready-to-copy|unknown|n\/a|tbd|dimensions recorded in source material)\b/i;
const genericStatementPattern = /\b(explores the relationship|acts as a space|creates dialogue|questions boundaries|liminal|poetic resonance|embodied experience)\b/i;

export function renderPortfolioPackage(input: PortfolioRenderInput) {
  const outputBaseName = safeOutputBaseName(input.outputBaseName || "portfolio");
  const imageBySource = new Map(input.copiedImages.map((image) => [image.sourcePath, image]));
  const html = renderPortfolioHtml(input.plan, imageBySource);
  const htmlFileName = outputBaseName === "portfolio" ? "portfolio.html" : `${outputBaseName}.html`;
  const pdfFileName = outputBaseName === "portfolio" ? "portfolio.pdf" : `${outputBaseName}.pdf`;
  const reportFileName = outputBaseName === "portfolio" ? "portfolio-visual-check.json" : `portfolio-visual-check-${outputBaseName}.json`;
  const htmlPath = path.join(input.externalDir, htmlFileName);
  fs.writeFileSync(htmlPath, html, "utf8");

  const pdfPath = renderHtmlToPdf(htmlPath, path.join(input.externalDir, pdfFileName));
  const visualReport = runVisualGate({ ...input, htmlPath, pdfPath });
  fs.writeFileSync(path.join(input.internalDir, reportFileName), JSON.stringify(visualReport, null, 2), "utf8");
  return { htmlPath, pdfPath, visualReport };
}

function renderPortfolioHtml(plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>) {
  const designSystem = plan.designSystem || defaultDesignSystem("quiet_white");
  return `<!doctype html>
<html lang="${escapeHtml(plan.language || "en")}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(plan.artistName || "Artist")} - ${escapeHtml(plan.portfolioTitle || "Selected Works")}</title>
<style>
@page { size: A4; margin: 0; }
* { box-sizing: border-box; }
body { margin: 0; color: ${designSystem.theme.text}; background: ${designSystem.theme.background}; font-family: Arial, Helvetica, sans-serif; }
.page { position: relative; width: 210mm; min-height: 297mm; break-after: page; display: flex; flex-direction: column; justify-content: center; gap: 8mm; padding: 19mm 18mm 18mm; overflow: hidden; background: var(--page-bg, ${designSystem.theme.background}); color: var(--page-text, ${designSystem.theme.text}); }
.page::before { content: ""; position: absolute; inset: 0; pointer-events: none; }
.page[data-bg="accent_panel"]::before { left: 0; width: 38mm; background: color-mix(in srgb, var(--accent) 18%, transparent); }
.page[data-bg="split_field"]::before { left: auto; width: 47%; background: color-mix(in srgb, var(--accent) 13%, transparent); }
.page[data-bg="soft_block"]::before { inset: 13mm; border: 1px solid color-mix(in srgb, var(--accent) 28%, transparent); }
.page-content { position: relative; z-index: 1; display: contents; }
.cover { justify-content: center; gap: 7mm; padding-left: 24mm; padding-right: 24mm; }
.cover h1 { margin: 0; max-width: 142mm; font-size: 30px; line-height: 1.12; font-weight: 500; letter-spacing: 0; }
.cover .subtitle { margin: 0; font-size: 15px; line-height: 1.45; color: var(--secondary); }
.cover .meta { margin: 0; font-size: 10.5px; line-height: 1.5; color: var(--secondary); }
.section-kicker { margin: 0 0 3mm; color: var(--accent); font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.08em; }
.statement { justify-content: center; }
.statement p { width: 128mm; margin: 0; font-size: 12px; line-height: 1.7; }
.work-title { margin: 0; font-size: 15px; line-height: 1.32; font-weight: 500; }
.work-image, img { background: transparent; }
.work-image { display: block; width: 100%; max-height: 204mm; object-fit: contain; object-position: center; ${imageFrameCss(designSystem)} }
.caption-below .work-image { max-height: 190mm; }
.text-image { display: grid; grid-template-columns: 48mm 1fr; gap: 12mm; align-items: center; }
.text-image p.note { margin: 0; font-size: 10.5px; line-height: 1.6; color: var(--secondary); }
.two-image { display: grid; grid-template-columns: 1fr; gap: 6mm; }
.two-image img { width: 100%; max-height: 94mm; object-fit: contain; ${imageFrameCss(designSystem)} }
.detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.detail-grid img { width: 100%; max-height: 84mm; object-fit: contain; ${imageFrameCss(designSystem)} }
.series-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.series-grid-large { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 7mm; align-items: center; }
.series-grid-large img { width: 100%; max-height: 86mm; object-fit: contain; ${imageFrameCss(designSystem)} }
.series-grid img { width: 100%; max-height: 78mm; object-fit: contain; ${imageFrameCss(designSystem)} }
.installation-spread .primary { max-height: 136mm; }
.installation-spread .detail-grid img { max-height: 58mm; }
.caption { margin: 0; max-width: 150mm; font-size: 9.5px; line-height: 1.45; color: var(--secondary); background: var(--caption-bg); padding: 2mm 0 0; }
.list-page { justify-content: center; }
.list-page h2 { margin: 0 0 6mm; font-size: 15px; font-weight: 500; }
.list-page p, .list-page li { font-size: 10.5px; line-height: 1.55; }
.list-page ul { margin: 0; padding-left: 5mm; }
.folio { position: absolute; right: 18mm; bottom: 9mm; font-size: 8.5px; color: var(--secondary); z-index: 2; }
</style>
</head>
<body style="--page-bg:${designSystem.theme.background};--page-text:${designSystem.theme.text};--secondary:${designSystem.theme.secondaryText};--accent:${designSystem.theme.accent};--caption-bg:${designSystem.theme.captionBackground || "transparent"}">
${normalizedPages(plan).map((page, index) => renderPage(page, plan, imageBySource, designSystem, index + 1)).join("\n")}
</body>
</html>
`;
}

function normalizedPages(plan: PortfolioPlan): PortfolioPlanPage[] {
  if (plan.pages.some((page) => page.type === "cover")) return plan.pages;
  return [
    {
      type: "cover",
      title: plan.artistName,
      subtitle: plan.portfolioTitle || "Selected Works",
      year: plan.year
    },
    ...plan.pages
  ];
}

function renderPage(page: PortfolioPlanPage, plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>, designSystem: PortfolioDesignSystem, pageNumber: number) {
  const design = page.design || pageDesignFor(page, designSystem.themeName);
  const open = `<section class="page ${pageClass(page)}" data-layout="${escapeHtml(page.layoutStrategy || page.type)}" data-bg="${escapeHtml(design.backgroundMode)}"><div class="page-content">`;
  const close = `</div>${design.pageNumber === false || designSystem.pageNumberStyle === "none" ? "" : `<span class="folio">${pageNumber}</span>`}</section>`;
  if (page.type === "cover") {
    return `${open}
  <h1>${escapeHtml(page.title || plan.artistName)}</h1>
  <p class="subtitle">${escapeHtml(page.subtitle || plan.portfolioTitle || "Selected Works")}</p>
  ${page.year || plan.year ? `<p class="meta">${escapeHtml(page.year || plan.year)}</p>` : ""}
  ${page.contact ? `<p class="meta">${escapeHtml(page.contact)}</p>` : ""}
${close}`;
  }

  if (page.type === "short_statement") {
    return `${open}<p>${escapeHtml(page.text)}</p>${close}`;
  }

  if (page.type === "project_opener") {
    return `${open}
  <p class="section-kicker">${escapeHtml(page.projectGroup || "Project")}</p>
  <p class="work-title">${escapeHtml(page.title)}</p>
  <p>${escapeHtml(page.text || "")}</p>
${close}`;
  }

  if (page.type === "work_full_page" || page.type === "single_work_full_page") {
    const image = imageBySource.get(page.imagePath);
    return `${open}
  ${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
${close}`;
  }

  if (page.type === "image_with_caption_below") {
    const image = imageBySource.get(page.images[0]?.path || "");
    return `${open}
  ${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
${close}`;
  }

  if (page.type === "text_left_image_right" || page.type === "text_image_context") {
    const image = imageBySource.get(page.images[0]?.path || "");
    return `${open}
  <p class="note">${escapeHtml(page.text || "")}</p>
  <div>${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}<p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p></div>
${close}`;
  }

  if (page.type === "two_image_detail_spread" || page.type === "two_image_spread") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied).slice(0, 2);
    return `${open}
  <div class="two-image">${images.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
${close}`;
  }

  if (page.type === "work_with_details" || page.type === "single_work_with_detail" || page.type === "installation_spread" || page.type === "installation_overview" || page.type === "installation_with_details") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied);
    const first = images[0];
    const rest = images.slice(1, 4);
    return `${open}
  ${first?.copied ? `<img class="work-image primary" src="images/${escapeHtml(first.copied.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  ${rest.length ? `<div class="detail-grid">${rest.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
${close}`;
  }

  if (page.type === "series_grid" || page.type === "series_grid_large" || page.type === "series_overview_grid" || page.type === "image_research_grid") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied).slice(0, page.type === "series_grid_large" ? 4 : 4);
    return `${open}
  <div class="${page.type === "series_grid_large" ? "series-grid-large" : "series-grid"}">${images.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
${close}`;
  }

  const listPage = page as Extract<PortfolioPlanPage, { type: "contact" | "contact_page" | "selected_works_list" }>;
  const listItems = listPage.works?.length ? `<ul>${listPage.works.map((item: string) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>` : "";
  return `${open}
  ${listPage.title ? `<h2>${escapeHtml(listPage.title)}</h2>` : ""}
  ${listPage.text ? `<p>${escapeHtml(listPage.text)}</p>` : ""}
  ${listItems}
${close}`;
}

function renderImage(planImage: PortfolioPlanImage, copied: CopiedPortfolioImage | undefined, fallbackAlt: string) {
  if (!copied) return "";
  return `<img src="images/${escapeHtml(copied.targetFileName)}" alt="${escapeHtml(planImage.caption || fallbackAlt)}" />`;
}

function pageClass(page: PortfolioPlanPage) {
  if (page.type === "cover") return "cover";
  if (page.type === "short_statement" || page.type === "project_opener") return "statement";
  if (page.type.includes("installation")) return "installation-spread";
  if (page.type === "selected_works_list" || page.type === "contact" || page.type === "contact_page") return "list-page";
  if (page.type.includes("grid")) return "series";
  if (page.type === "text_left_image_right" || page.type === "text_image_context") return "text-image";
  return "work-page";
}

function pageDesignFor(page: PortfolioPlanPage, themeName: PortfolioThemeName) {
  if (page.type === "cover") return { themeName, backgroundMode: "accent_panel" as const, emphasis: "section" as const, pageNumber: false };
  if (page.type === "short_statement") return { themeName, backgroundMode: "soft_block" as const, emphasis: "text" as const };
  if (page.type === "project_opener") return { themeName, backgroundMode: "split_field" as const, emphasis: "section" as const };
  if (page.type.includes("installation")) return { themeName, backgroundMode: "plain" as const, emphasis: "image" as const };
  if (page.type.includes("grid")) return { themeName, backgroundMode: "soft_block" as const, emphasis: "balanced" as const };
  if (page.type === "text_left_image_right" || page.type === "text_image_context") return { themeName, backgroundMode: "split_field" as const, emphasis: "balanced" as const };
  if (page.type === "selected_works_list" || page.type === "contact" || page.type === "contact_page") return { themeName, backgroundMode: "accent_panel" as const, emphasis: "text" as const };
  return { themeName, backgroundMode: "plain" as const, emphasis: "image" as const };
}

function defaultDesignSystem(themeName: PortfolioThemeName): PortfolioDesignSystem {
  const themes: Record<PortfolioThemeName, PortfolioDesignSystem["theme"]> = {
    quiet_white: { name: "quiet_white", background: "#f7f6f2", text: "#171717", secondaryText: "#5a5650", accent: "#7b6f5f", captionBackground: "rgba(247,246,242,0.88)", imageFrame: "hairline" },
    warm_archive: { name: "warm_archive", background: "#eee8dc", text: "#1e1b17", secondaryText: "#625b50", accent: "#8a6f45", captionBackground: "rgba(238,232,220,0.9)", imageFrame: "inset_panel" },
    soft_gray_gallery: { name: "soft_gray_gallery", background: "#e7e8e5", text: "#181a1a", secondaryText: "#555b59", accent: "#6b746f", captionBackground: "rgba(231,232,229,0.9)", imageFrame: "soft_shadow" },
    dark_installation: { name: "dark_installation", background: "#202120", text: "#f0eee8", secondaryText: "#b9b5aa", accent: "#9f8d65", captionBackground: "rgba(32,33,32,0.82)", imageFrame: "none" },
    image_research_bluegray: { name: "image_research_bluegray", background: "#e4e9eb", text: "#151b1f", secondaryText: "#53616a", accent: "#557184", captionBackground: "rgba(228,233,235,0.9)", imageFrame: "hairline" },
    painting_color_field: { name: "painting_color_field", background: "#f1efe7", text: "#191815", secondaryText: "#5e584e", accent: "#8f604d", captionBackground: "rgba(241,239,231,0.9)", imageFrame: "soft_shadow" }
  };
  return { themeName, theme: themes[themeName], headingScale: "quiet", pageNumberStyle: "bottom_right", marginSystem: "gallery", sectionDividerStyle: "rule" };
}

function imageFrameCss(designSystem: PortfolioDesignSystem) {
  if (designSystem.theme.imageFrame === "soft_shadow") return "box-shadow: 0 3mm 9mm rgba(0,0,0,0.15);";
  if (designSystem.theme.imageFrame === "hairline") return "border: 0.25mm solid color-mix(in srgb, var(--secondary) 24%, transparent);";
  if (designSystem.theme.imageFrame === "inset_panel") return "padding: 2mm; background: rgba(255,255,255,0.24); border: 0.25mm solid color-mix(in srgb, var(--accent) 22%, transparent);";
  return "";
}

function buildCaption(page: Extract<PortfolioPlanPage, { title: string; year?: string; medium?: string; dimensions?: string }>) {
  const year = "year" in page ? page.year : undefined;
  const medium = "medium" in page ? page.medium : undefined;
  const dimensions = "dimensions" in page ? page.dimensions : undefined;
  return [page.title, year, medium, dimensions].filter((item) => item && !/unknown|n\/a|tbd/i.test(item)).join(", ");
}

function runVisualGate(input: PortfolioRenderInput & { htmlPath: string; pdfPath: string | null }): PortfolioVisualGateResult {
  const autoFixableIssues: PortfolioIssueClassification[] = [];
  const blockingIssues: PortfolioIssueClassification[] = [];
  const warnings: PortfolioIssueClassification[] = [];
  const suggestedRepairs: string[] = [];
  const pageCount = normalizedPages(input.plan).length;
  const externalText = fs.readFileSync(input.htmlPath, "utf8");
  const pdfSizeBytes = input.pdfPath && fs.existsSync(input.pdfPath) ? fs.statSync(input.pdfPath).size : 0;
  const usedFallbackPdf = Boolean(input.pdfPath && isFallbackPdf(input.pdfPath));
  const constraints = input.plan.portfolioConstraints || { targetPages: 20, minimumPages: 16, maximumPages: input.plan.maxPages || 24 };
  const maxPages = constraints.maximumPages || input.plan.maxPages;
  const targetFileSizeMb = input.plan.targetFileSizeMb;
  const workImagePages = input.plan.pages.filter((page) => page.type === "work_full_page" || page.type === "single_work_full_page" || "images" in page);
  const strategies = input.plan.pages.map((page) => page.layoutStrategy || page.type);
  const aestheticDiagnostics = buildAestheticDiagnostics(input.plan, externalText, input.copiedImages);
  const layoutStrategyCounts = countBy(strategies);
  const themeCounts = countBy(input.plan.pages.map((page) => page.design?.themeName || input.plan.designSystem?.themeName || "quiet_white"));
  const repeatedLayoutRuns = repeatedRuns(strategies, 4);
  const smallImagePages = findSmallImagePages(input.plan, input.copiedImages);
  const captionIssues = findCaptionIssues(input.plan);
  const webPreviewLanguageHits = aestheticDiagnostics.forbiddenExternalWords.filter((word) => /preview|mock|draft|placeholder|test/.test(word));

  for (const issue of input.preflightIssues) {
    if (/references no formal image paths|no structured|no image-bearing/i.test(issue)) blockingIssues.push(classify("no_usable_images", issue, "blocking"));
    else autoFixableIssues.push(classify("image_preflight", issue, "auto_fixable"));
  }
  if (!input.pdfPath) autoFixableIssues.push(classify("pdf_not_rendered", "Portfolio PDF was not rendered; retry or HTML remains available for inspection.", "auto_fixable"));
  if (usedFallbackPdf) blockingIssues.push(classify("fallback_pdf_not_professional", "Fallback PDF renderer was used; package is not professionally ready unless Playwright produces the final PDF.", "blocking"));
  if (forbiddenExternalPattern.test(externalText)) autoFixableIssues.push(classify("forbidden_terms", "Portfolio HTML contains forbidden external-facing terms.", "auto_fixable"));
  if (aestheticDiagnostics.forbiddenExternalWords.length) autoFixableIssues.push(classify("forbidden_terms", `Portfolio contains inappropriate external-facing words: ${aestheticDiagnostics.forbiddenExternalWords.join(", ")}.`, "auto_fixable"));
  if (aestheticDiagnostics.readsAsHtmlPreview) autoFixableIssues.push(classify("reads_as_html_preview", "Portfolio output reads as an HTML/browser preview instead of a formal PDF.", "auto_fixable"));
  if (genericStatementPattern.test(externalText)) autoFixableIssues.push(classify("statement_too_generic", "Portfolio statement contains generic application-language phrasing.", "auto_fixable"));
  if (pageCount < constraints.minimumPages) autoFixableIssues.push(classify("page_count_too_low", `Portfolio has ${pageCount} pages, below minimum ${constraints.minimumPages}.`, "auto_fixable"));
  if (maxPages && pageCount > maxPages) autoFixableIssues.push(classify("page_count_too_high", `Portfolio has ${pageCount} pages, exceeding maximum ${maxPages}.`, "auto_fixable"));
  if (targetFileSizeMb && pdfSizeBytes > targetFileSizeMb * 1024 * 1024) autoFixableIssues.push(classify("pdf_too_large", `Portfolio PDF is ${(pdfSizeBytes / 1024 / 1024).toFixed(2)} MB, exceeding target ${targetFileSizeMb} MB.`, "auto_fixable"));
  if (input.webResearchReferences.length < 3) warnings.push(classify("limited_references", "Fewer than three portfolio design/application references were recorded.", "warning"));
  if (workImagePages.length === 0) blockingIssues.push(classify("no_usable_images", "Portfolio plan has no image-bearing work pages.", "blocking"));
  if (!input.plan.layoutResearchUsed || input.plan.layoutResearchUsed.derivedPrinciples.length < 5) autoFixableIssues.push(classify("portfolio_research_missing", "Portfolio layout research is missing or too thin.", "auto_fixable"));
  if (!input.plan.layoutResearchUsed || input.plan.layoutResearchUsed.appliedPrinciples.length === 0) autoFixableIssues.push(classify("portfolio_research_not_applied", "Portfolio layout research was recorded but not applied to PortfolioPlan.", "auto_fixable"));
  if (!input.plan.curatorialSummary?.passedDiversityGate) {
    const availableSingleSeries = input.plan.curatorialSummary?.projectGroupCount <= 1 && input.plan.portfolioTitle !== "Selected Works";
    if (!availableSingleSeries) autoFixableIssues.push(classify("curatorial_gate_failed", "Portfolio did not pass project diversity, page rhythm, or layout strategy checks.", "auto_fixable"));
  }

  for (const copied of input.copiedImages) {
    if (copied.tooSmallForFullPage) autoFixableIssues.push({ ...classify("small_full_page_image", `Image may be too small for full-page use: ${copied.sourcePath} (${copied.width}x${copied.height}).`, "auto_fixable"), sourcePath: copied.sourcePath });
  }
  const plannedImageUses = input.plan.pages.flatMap((page, index) => {
    if (page.type === "work_full_page" || page.type === "single_work_full_page") return [{ path: page.imagePath, page: index + 1, layout: "single_work_full_page" }];
    if ("images" in page) return page.images.map((image) => ({ path: image.path, page: index + 1, layout: page.layoutStrategy || page.type }));
    return [];
  }).filter((use) => use.path);
  const plannedImagePaths = plannedImageUses.map((use) => use.path);
  const duplicateImages = excessiveDuplicateImagePaths(plannedImageUses);
  const copiedSourcePaths = new Set(input.copiedImages.map((image) => image.sourcePath));
  const missingReferencedImages = plannedImagePaths.filter((imagePath) => !copiedSourcePaths.has(imagePath));
  if (missingReferencedImages.length) blockingIssues.push(classify("missing_referenced_image", `Portfolio references ${missingReferencedImages.length} image file(s) that were not copied/readable.`, "blocking"));
  if (duplicateImages.length) autoFixableIssues.push(classify("duplicate_images", `Portfolio overuses ${new Set(duplicateImages).size} image file(s) beyond overview-to-detail rhythm.`, "auto_fixable"));
  for (const page of input.plan.pages) {
    if ("caption" in page && page.caption && page.caption.split(/\s+/).filter(Boolean).length > 35) autoFixableIssues.push(classify("caption_too_long", `Caption is longer than 35 words on page ${input.plan.pages.indexOf(page) + 1}.`, "auto_fixable"));
    if ((page.type === "series_grid" || page.type === "series_grid_large" || page.type === "series_overview_grid" || page.type === "image_research_grid") && page.images.length > 4) autoFixableIssues.push(classify("series_grid_too_dense", `Series grid has ${page.images.length} images and should be split into larger pages.`, "auto_fixable"));
  }
  if (new Set(strategies).size < Math.min(5, Math.max(3, input.plan.pages.length - 2))) autoFixableIssues.push(classify("layout_strategy_diversity_too_low", "Portfolio uses fewer than five layout strategies when material allows.", "auto_fixable"));
  if (aestheticDiagnostics.longestLayoutRun > 3) autoFixableIssues.push(classify("too_many_consecutive_layout_strategy", "More than three consecutive pages use the same layout strategy.", "auto_fixable"));
  if (aestheticDiagnostics.whiteOnlyPageCount > Math.ceil(pageCount * 0.7) && input.plan.designSystem?.themeName === "quiet_white") autoFixableIssues.push(classify("white_only_monotony", "Too many pages use a raw white/near-white page system without section rhythm.", "auto_fixable"));
  if (smallImagePages.length > 0) autoFixableIssues.push(classify("images_too_small_relative_to_page", `${smallImagePages.length} image page(s) appear too small relative to the page.`, "auto_fixable"));
  if (captionIssues.length > 0) autoFixableIssues.push(classify("captions_too_dense", `${captionIssues.length} page(s) have dense captions/text blocks.`, "auto_fixable"));
  if (/test preview|web preview|browser preview|mock|draft|placeholder/i.test(JSON.stringify(input.plan.pages.slice(0, 2)))) autoFixableIssues.push(classify("cover_looks_like_dev_page", "Cover or opening page contains development/preview language.", "auto_fixable"));

  const domCheck = tryCheckHtmlLayout(input.htmlPath);
  const pageScreenshots = safeOutputBaseName(input.outputBaseName || "portfolio") === "portfolio"
    ? capturePortfolioPageScreenshots(input.htmlPath, input.internalDir, "portfolio")
    : [];
  for (const issue of domCheck.issues) autoFixableIssues.push(classify(issue.includes("caption") ? "caption_too_small" : "layout_balance", issue, "auto_fixable"));
  const blankOrSparsePages = domCheck.issues.flatMap((issue) => {
    const match = issue.match(/Page\s+(\d+).*?(?:blank|short|sparse|small)/i);
    return match ? [Number(match[1])] : [];
  });
  const whiteOnlyPageRatio = pageCount ? aestheticDiagnostics.whiteOnlyPageCount / pageCount : 0;
  const aestheticScore = scoreAesthetic({
    pageCount,
    layoutStrategyCount: aestheticDiagnostics.layoutStrategyCount,
    longestLayoutRun: aestheticDiagnostics.longestLayoutRun,
    whiteOnlyPageRatio,
    blankOrSparsePages,
    smallImagePages,
    captionIssues,
    webPreviewLanguageHits
  });
  const professionalPdfScore = scoreProfessionalPdf({
    pdfPath: input.pdfPath,
    pdfSizeBytes,
    usedFallbackPdf,
    pageCount,
    constraints,
    missingImages: missingReferencedImages,
    webPreviewLanguageHits,
    aestheticScore
  });
  if (aestheticScore < 85) autoFixableIssues.push(classify("aesthetic_score_too_low", `Portfolio aesthetic score is ${aestheticScore}, below required 85.`, "auto_fixable"));
  if (professionalPdfScore < 85) autoFixableIssues.push(classify("professional_pdf_score_too_low", `Portfolio professional PDF score is ${professionalPdfScore}, below required 85.`, "auto_fixable"));
  suggestedRepairs.push(...autoFixableIssues.map((issue) => repairSuggestion(issue.code)));

  return {
    checkedAt: new Date().toISOString(),
    method: "HTML rendered with Playwright when available; PDF existence, page count, file size, text, image asset, and DOM layout checks.",
    opportunityTitle: input.opportunity.title,
    pageCount,
    targetPages: constraints.targetPages,
    minimumPages: constraints.minimumPages,
    maximumPages: constraints.maximumPages,
    pdfPath: input.pdfPath,
    pdfSizeBytes,
    pageScreenshots,
    layoutStrategyCounts,
    themeCounts,
    repeatedLayoutRuns,
    blankOrSparsePages,
    whiteOnlyPageRatio,
    webPreviewLanguageHits,
    missingImages: missingReferencedImages,
    smallImagePages,
    captionIssues,
    aestheticScore,
    professionalPdfScore,
    usedFallbackPdf,
    autoFixableIssues,
    blockingIssues,
    warnings,
    suggestedRepairs,
    copiedImages: input.copiedImages,
    aestheticDiagnostics,
    domCheck,
    passed: blockingIssues.length === 0 && autoFixableIssues.length === 0
  };
}

function buildAestheticDiagnostics(plan: PortfolioPlan, html: string, copiedImages: CopiedPortfolioImage[]): PortfolioVisualGateResult["aestheticDiagnostics"] {
  const themeName = plan.designSystem?.themeName || "quiet_white";
  const whiteOnlyPageCount = themeName === "quiet_white"
    ? plan.pages.filter((page) => !page.design || page.design.backgroundMode === "plain").length
    : 0;
  const strategies = plan.pages.map((page) => page.layoutStrategy || page.type);
  const longestLayoutRun = longestRun(strategies);
  const copiedBySource = new Map(copiedImages.map((image) => [image.sourcePath, image]));
  const pagesWithLikelySmallImages = plan.pages.filter((page) => {
    const images = page.type === "work_full_page" || page.type === "single_work_full_page"
      ? [copiedBySource.get(page.imagePath)]
      : "images" in page
        ? page.images.map((image) => copiedBySource.get(image.path))
        : [];
    return images.some((image) => image && (Math.max(image.width, image.height) < 1600 || Math.min(image.width, image.height) < 850));
  }).length;
  const pagesWithDenseCaptions = plan.pages.filter((page) => {
    const text = [
      "caption" in page ? page.caption : "",
      "text" in page ? page.text : "",
      page.type === "selected_works_list" ? page.works?.join(" ") : ""
    ].filter(Boolean).join(" ");
    return text.split(/\s+/).filter(Boolean).length > 60;
  }).length;
  const forbiddenExternalWords = [...new Set((html.match(/\b(?:TEST PREVIEW|Web preview|browser preview|mock|draft|placeholder|generated by AI|unknown|N\/A|TBD)\b/gi) || []).map((item) => item.toLowerCase()))];
  return {
    whiteOnlyPageCount,
    layoutStrategyCount: new Set(strategies).size,
    longestLayoutRun,
    pagesWithLikelySmallImages,
    pagesWithDenseCaptions,
    forbiddenExternalWords,
    readsAsHtmlPreview: /\bportfolio\.html\b|web preview|browser preview|test preview/i.test(html)
  };
}

function countBy(values: string[]) {
  return values.reduce<Record<string, number>>((counts, value) => {
    counts[value] = (counts[value] || 0) + 1;
    return counts;
  }, {});
}

function repeatedRuns(values: string[], minimumLength: number) {
  const runs: Array<{ strategy: string; startPage: number; length: number }> = [];
  let current = "";
  let start = 0;
  let length = 0;
  values.forEach((value, index) => {
    if (value === current) {
      length += 1;
    } else {
      if (current && length >= minimumLength) runs.push({ strategy: current, startPage: start + 1, length });
      current = value;
      start = index;
      length = 1;
    }
  });
  if (current && length >= minimumLength) runs.push({ strategy: current, startPage: start + 1, length });
  return runs;
}

function findSmallImagePages(plan: PortfolioPlan, copiedImages: CopiedPortfolioImage[]) {
  const copiedBySource = new Map(copiedImages.map((image) => [image.sourcePath, image]));
  return plan.pages.flatMap((page, index) => {
    const images = page.type === "work_full_page" || page.type === "single_work_full_page"
      ? [copiedBySource.get(page.imagePath)]
      : "images" in page
        ? page.images.map((image) => copiedBySource.get(image.path))
        : [];
    return images.some((image) => image && (Math.max(image.width, image.height) < 1600 || Math.min(image.width, image.height) < 850)) ? [index + 1] : [];
  });
}

function excessiveDuplicateImagePaths(uses: Array<{ path: string; page: number; layout: string }>) {
  const byPath = new Map<string, Array<{ page: number; layout: string }>>();
  for (const use of uses) byPath.set(use.path, [...(byPath.get(use.path) || []), { page: use.page, layout: use.layout }]);
  const excessive: string[] = [];
  for (const [imagePath, imageUses] of byPath) {
    const fullPageUses = imageUses.filter((use) => /single_work_full_page|work_full_page/.test(use.layout)).length;
    const overviewUses = imageUses.filter((use) => /overview|grid/.test(use.layout)).length;
    const nonOverviewUses = imageUses.length - overviewUses;
    if (imageUses.length > 2 || fullPageUses > 1 || nonOverviewUses > 1) excessive.push(imagePath);
  }
  return excessive;
}

function findCaptionIssues(plan: PortfolioPlan) {
  return plan.pages.flatMap((page, index) => {
    const issues: Array<{ page: number; issue: string }> = [];
    const caption = "caption" in page ? page.caption || "" : "";
    if (caption.split(/\s+/).filter(Boolean).length > 35) issues.push({ page: index + 1, issue: "caption longer than 35 words" });
    if (page.type === "short_statement" || page.type === "selected_works_list" || page.type === "contact" || page.type === "contact_page") return issues;
    const text = [
      caption,
      "text" in page ? page.text || "" : "",
    ].filter(Boolean).join(" ");
    if (text.split(/\s+/).filter(Boolean).length > 60) issues.push({ page: index + 1, issue: "page text/caption block is too dense" });
    return issues;
  });
}

function scoreAesthetic(input: {
  pageCount: number;
  layoutStrategyCount: number;
  longestLayoutRun: number;
  whiteOnlyPageRatio: number;
  blankOrSparsePages: number[];
  smallImagePages: number[];
  captionIssues: Array<{ page: number; issue: string }>;
  webPreviewLanguageHits: string[];
}) {
  let score = 100;
  if (input.pageCount >= 16 && input.layoutStrategyCount < 5) score -= 18;
  if (input.longestLayoutRun > 3) score -= (input.longestLayoutRun - 3) * 8;
  if (input.whiteOnlyPageRatio > 0.7) score -= 12;
  score -= Math.min(16, input.blankOrSparsePages.length * 4);
  score -= Math.min(12, input.smallImagePages.length * 3);
  score -= Math.min(12, input.captionIssues.length * 3);
  if (input.webPreviewLanguageHits.length) score -= 25;
  return Math.max(0, Math.min(100, Math.round(score)));
}

function scoreProfessionalPdf(input: {
  pdfPath: string | null;
  pdfSizeBytes: number;
  usedFallbackPdf: boolean;
  pageCount: number;
  constraints: { minimumPages: number; maximumPages: number };
  missingImages: string[];
  webPreviewLanguageHits: string[];
  aestheticScore: number;
}) {
  let score = input.aestheticScore;
  if (!input.pdfPath || input.pdfSizeBytes === 0) score -= 40;
  if (input.usedFallbackPdf) score -= 35;
  if (input.pageCount < input.constraints.minimumPages || input.pageCount > input.constraints.maximumPages) score -= 20;
  if (input.missingImages.length) score -= 30;
  if (input.webPreviewLanguageHits.length) score -= 25;
  return Math.max(0, Math.min(100, Math.round(score)));
}

function isFallbackPdf(pdfPath: string) {
  try {
    const header = fs.readFileSync(pdfPath, "utf8").slice(0, 120);
    return header.includes("ARTIST_STUDIO_FALLBACK_PDF");
  } catch {
    return false;
  }
}

function longestRun(values: string[]) {
  let longest = 0;
  let current = 0;
  let previous = "";
  for (const value of values) {
    current = value === previous ? current + 1 : 1;
    previous = value;
    longest = Math.max(longest, current);
  }
  return longest;
}

function classify(code: string, message: string, severity: PortfolioIssueClassification["severity"]): PortfolioIssueClassification {
  return { code, message, severity };
}

function repairSuggestion(code: string) {
  const suggestions: Record<string, string> = {
    page_count_too_low: "Add detail, context, installation, or selected-works-list pages.",
    page_count_too_high: "Remove secondary detail pages or merge minor works.",
    forbidden_terms: "Rewrite captions/statement without internal or placeholder words.",
    small_full_page_image: "Move image to detail layout or use an alternate higher-resolution file.",
    pdf_too_large: "Optimize images and rerender PDF.",
    caption_too_small: "Increase caption size or reduce caption length.",
    caption_too_long: "Compress the caption to a formal 20-35 word maximum.",
    statement_too_generic: "Rewrite the statement with concrete materials, image sources, making methods, and display context.",
    series_grid_too_dense: "Split dense grids into overview and detail pages.",
    duplicate_images: "Remove duplicate image uses or assign them to distinct detail/context roles.",
    layout_balance: "Rebalance page layout and rerender.",
    curatorial_gate_failed: "Regroup works by project, vary page roles, and rerender.",
    portfolio_research_missing: "Run portfolio layout research and record principles before planning.",
    portfolio_research_not_applied: "Apply research principles to project grouping, page rhythm, captions, and selected works list.",
    layout_strategy_diversity_too_low: "Introduce opener, grid, detail, installation/context, list, and contact pages.",
    too_many_consecutive_full_page_works: "Convert repeated full-page images into grids, spreads, or context pages.",
    too_many_consecutive_layout_strategy: "Reorder pages and convert repeated pages into grid, context, detail, or opener layouts.",
    white_only_monotony: "Select a restrained non-white theme or add accent/soft-block section rhythm.",
    reads_as_html_preview: "Remove HTML/browser-preview wording and rerender as a formal PDF artifact.",
    cover_looks_like_dev_page: "Rewrite cover/opening page without development language.",
    images_too_small_relative_to_page: "Move low-resolution images into grid/detail layouts or replace with stronger images.",
    captions_too_dense: "Compress captions and move longer context to a statement or project opener.",
    missing_referenced_image: "Block readiness until all referenced image paths are readable and copied.",
    fallback_pdf_not_professional: "Install/use Playwright Chromium and rerender the formal PDF.",
    aesthetic_score_too_low: "Repair layout diversity, image scale, captions, theme rhythm, and opening pages.",
    professional_pdf_score_too_low: "Rerender a real Playwright PDF after fixing aesthetic and missing-image issues."
  };
  return suggestions[code] || "Automatically adjust PortfolioPlan and rerender.";
}

function tryCheckHtmlLayout(htmlPath: string) {
  try {
    requireFromRenderer.resolve("playwright");
    const childProcess = requireFromRenderer("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage({ viewport: { width: 794, height: 1123 } });
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          const result = await page.evaluate(() => {
            const issues = [];
            const pages = Array.from(document.querySelectorAll(".page"));
            pages.forEach((page, index) => {
              const rect = page.getBoundingClientRect();
              const images = Array.from(page.querySelectorAll("img"));
              if (images.length) {
                const visibleImages = images.filter((img) => {
                  const r = img.getBoundingClientRect();
                  return r.width >= 180 && r.height >= 160 && img.complete && img.naturalWidth > 0;
                });
                if (!visibleImages.length) issues.push(\`Page \${index + 1} has image tags but no clearly visible loaded image.\`);
              }
              const caption = page.querySelector(".caption");
              if (caption) {
                const fontSize = Number.parseFloat(getComputedStyle(caption).fontSize);
                if (fontSize < 8.5) issues.push(\`Page \${index + 1} caption font is below readable size.\`);
              }
              if (rect.height < 700) issues.push(\`Page \${index + 1} appears too short or mostly blank.\`);
            });
            return { pageCount: pages.length, issues };
          });
          console.log(JSON.stringify(result));
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    const output = childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      encoding: "utf8",
      timeout: 30000
    });
    return JSON.parse(output) as { pageCount: number; issues: string[] };
  } catch (error) {
    return { pageCount: 0, issues: [`Playwright DOM visual check unavailable: ${error instanceof Error ? error.message : "unknown error"}`] };
  }
}

function capturePortfolioPageScreenshots(htmlPath: string, internalDir: string, outputBaseName: string) {
  try {
    requireFromRenderer.resolve("playwright");
    const childProcess = requireFromRenderer("node:child_process") as typeof import("node:child_process");
    const screenshotDirName = outputBaseName === "portfolio" ? "portfolio-page-screenshots" : `portfolio-page-screenshots-${outputBaseName}`;
    const screenshotDir = path.join(internalDir, screenshotDirName);
    fs.mkdirSync(screenshotDir, { recursive: true });
    const code = `
      const fs = require("node:fs");
      const path = require("node:path");
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage({ viewport: { width: 794, height: 1123 } });
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          const pages = await page.$$(".page");
          const paths = [];
          for (let index = 0; index < pages.length; index += 1) {
            const screenshotPath = path.join(${JSON.stringify(screenshotDir)}, "page-" + String(index + 1).padStart(2, "0") + ".png");
            await pages[index].screenshot({ path: screenshotPath });
            if (fs.existsSync(screenshotPath)) paths.push(screenshotPath);
          }
          console.log(JSON.stringify(paths));
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    const output = childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      encoding: "utf8",
      timeout: 45000
    });
    return (JSON.parse(output) as string[]).map((screenshotPath) => path.relative(internalDir, screenshotPath));
  } catch {
    return [];
  }
}

export function renderHtmlToPdf(htmlPath: string, pdfPath: string) {
  try {
    requireFromRenderer.resolve("playwright");
    const childProcess = requireFromRenderer("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage();
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          await page.pdf({ path: ${JSON.stringify(pdfPath)}, format: "A4", printBackground: true });
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      stdio: "ignore",
      timeout: 30000
    });
    return fs.existsSync(pdfPath) ? pdfPath : null;
  } catch {
    return renderFallbackPdfFromHtml(htmlPath, pdfPath);
  }
}

function safeOutputBaseName(value: string) {
  return value.replace(/[^a-z0-9-]+/gi, "-").replace(/^-+|-+$/g, "") || "portfolio";
}

function renderFallbackPdfFromHtml(htmlPath: string, pdfPath: string) {
  try {
    const html = fs.existsSync(htmlPath) ? fs.readFileSync(htmlPath, "utf8") : "";
    const title = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g, " ").trim() || "Portfolio";
    const pageTexts = Array.from(html.matchAll(/<section[^>]*class="[^"]*\bpage\b[^"]*"[^>]*>([\s\S]*?)<\/section>/gi))
      .map((match) => htmlToPlainText(match[1]))
      .filter(Boolean);
    writeSimplePdf(pdfPath, title, pageTexts.length ? pageTexts : [htmlToPlainText(html) || title]);
    return fs.existsSync(pdfPath) ? pdfPath : null;
  } catch {
    return null;
  }
}

function htmlToPlainText(html: string) {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<img\b[^>]*alt="([^"]*)"[^>]*>/gi, " $1 ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|h1|h2|li|pre|div)>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

function writeSimplePdf(pdfPath: string, title: string, pageTexts: string[]) {
  const objects: string[] = [];
  const addObject = (body: string) => {
    objects.push(body);
    return objects.length;
  };
  const catalogId = addObject("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = addObject("__PAGES__");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds: number[] = [];

  for (const [index, text] of pageTexts.entries()) {
    const content = buildPdfPageContent(index === 0 ? `${title}\n\n${text}` : text);
    const contentId = addObject(`<< /Length ${Buffer.byteLength(content, "binary")} >>\nstream\n${content}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  }
  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;
  objects[catalogId - 1] = "<< /Type /Catalog /Pages 2 0 R >>";

  let pdf = "%PDF-1.4\n%ARTIST_STUDIO_FALLBACK_PDF\n";
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(pdf, "binary"));
    pdf += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, "binary");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  fs.writeFileSync(pdfPath, pdf, "binary");
}

function buildPdfPageContent(text: string) {
  const lines = wrapPdfText(text, 86).slice(0, 44);
  const commands = ["BT", "/F1 10 Tf", "50 790 Td", "14 TL"];
  for (const line of lines) commands.push(`(${escapePdfText(line)}) Tj`, "T*");
  commands.push("ET");
  return commands.join("\n");
}

function wrapPdfText(text: string, width: number) {
  const words = text.replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?").split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > width) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
