import fs from "node:fs";
import path from "node:path";
import type { Opportunity, PortfolioPlan, PortfolioPlanImage, PortfolioPlanPage } from "@/types/domain";

export type CopiedPortfolioImage = {
  sourcePath: string;
  targetFileName: string;
  width: number;
  height: number;
  format: string;
  sizeBytes: number;
  optimized: boolean;
  tooSmallForFullPage: boolean;
};

type PortfolioRenderInput = {
  externalDir: string;
  internalDir: string;
  opportunity: Opportunity;
  plan: PortfolioPlan;
  copiedImages: CopiedPortfolioImage[];
  webResearchReferences: string[];
  preflightIssues: string[];
};

const forbiddenExternalPattern = /\b(mock|test pdf|review committee|draft|placeholder|generated by ai|for this open call|selected for|ready-to-copy|unknown|n\/a|tbd|dimensions recorded in source material)\b/i;

export function renderPortfolioPackage(input: PortfolioRenderInput) {
  const imageBySource = new Map(input.copiedImages.map((image) => [image.sourcePath, image]));
  const html = renderPortfolioHtml(input.plan, imageBySource);
  const htmlPath = path.join(input.externalDir, "portfolio.html");
  fs.writeFileSync(htmlPath, html, "utf8");

  const pdfPath = tryRenderPortfolioPdf(htmlPath, input.externalDir);
  const visualReport = runVisualGate({ ...input, htmlPath, pdfPath });
  fs.writeFileSync(path.join(input.internalDir, "portfolio-visual-check.json"), JSON.stringify(visualReport, null, 2), "utf8");
  return { htmlPath, pdfPath, visualReport };
}

function renderPortfolioHtml(plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>) {
  return `<!doctype html>
<html lang="${escapeHtml(plan.language || "en")}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(plan.artistName || "Artist")} - ${escapeHtml(plan.portfolioTitle || "Selected Works")}</title>
<style>
@page { size: A4; margin: 18mm; }
* { box-sizing: border-box; }
body { margin: 0; color: #191919; background: #fff; font-family: Arial, Helvetica, sans-serif; }
.page { width: 174mm; min-height: 261mm; break-after: page; display: flex; flex-direction: column; justify-content: center; gap: 8mm; }
.cover { justify-content: center; gap: 6mm; }
.cover h1 { margin: 0; font-size: 28px; line-height: 1.18; font-weight: 500; letter-spacing: 0; }
.cover .subtitle { margin: 0; font-size: 15px; line-height: 1.45; }
.cover .meta { margin: 0; font-size: 10.5px; line-height: 1.5; color: #4a4a4a; }
.statement { justify-content: center; }
.statement p { width: 135mm; margin: 0; font-size: 12px; line-height: 1.7; }
.work-title { margin: 0; font-size: 12px; line-height: 1.35; font-weight: 500; }
.work-image { display: block; width: 100%; max-height: 198mm; object-fit: contain; object-position: center; }
.detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.detail-grid img { width: 100%; max-height: 88mm; object-fit: contain; }
.series-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.series-grid img { width: 100%; max-height: 78mm; object-fit: contain; }
.installation-spread .primary { max-height: 135mm; }
.installation-spread .detail-grid img { max-height: 58mm; }
.caption { margin: 0; max-width: 150mm; font-size: 9.5px; line-height: 1.45; color: #2c2c2c; }
.list-page { justify-content: center; }
.list-page h2 { margin: 0 0 6mm; font-size: 14px; font-weight: 500; }
.list-page p, .list-page li { font-size: 10.5px; line-height: 1.55; }
.list-page ul { margin: 0; padding-left: 5mm; }
</style>
</head>
<body>
${normalizedPages(plan).map((page) => renderPage(page, plan, imageBySource)).join("\n")}
</body>
</html>
`;
}

function normalizedPages(plan: PortfolioPlan): PortfolioPlanPage[] {
  if (plan.pages.some((page) => page.type === "cover")) return plan.pages;
  return [
    {
      type: "cover",
      title: plan.artistName,
      subtitle: plan.portfolioTitle || "Selected Works",
      year: plan.year
    },
    ...plan.pages
  ];
}

function renderPage(page: PortfolioPlanPage, plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>) {
  if (page.type === "cover") {
    return `<section class="page cover">
  <h1>${escapeHtml(page.title || plan.artistName)}</h1>
  <p class="subtitle">${escapeHtml(page.subtitle || plan.portfolioTitle || "Selected Works")}</p>
  ${page.year || plan.year ? `<p class="meta">${escapeHtml(page.year || plan.year)}</p>` : ""}
  ${page.contact ? `<p class="meta">${escapeHtml(page.contact)}</p>` : ""}
</section>`;
  }

  if (page.type === "short_statement") {
    return `<section class="page statement"><p>${escapeHtml(page.text)}</p></section>`;
  }

  if (page.type === "work_full_page") {
    const image = imageBySource.get(page.imagePath);
    return `<section class="page work-page">
  ${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "work_with_details" || page.type === "installation_spread") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied);
    const first = images[0];
    const rest = images.slice(1, 4);
    return `<section class="page ${page.type === "installation_spread" ? "installation-spread" : "work-with-details"}">
  ${first?.copied ? `<img class="work-image primary" src="images/${escapeHtml(first.copied.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  ${rest.length ? `<div class="detail-grid">${rest.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "series_grid") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied).slice(0, 4);
    return `<section class="page series">
  <div class="series-grid">${images.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  const listPage = page as Extract<PortfolioPlanPage, { type: "contact" | "selected_works_list" }>;
  const listItems = listPage.works?.length ? `<ul>${listPage.works.map((item: string) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>` : "";
  return `<section class="page list-page">
  ${listPage.title ? `<h2>${escapeHtml(listPage.title)}</h2>` : ""}
  ${listPage.text ? `<p>${escapeHtml(listPage.text)}</p>` : ""}
  ${listItems}
</section>`;
}

function renderImage(planImage: PortfolioPlanImage, copied: CopiedPortfolioImage | undefined, fallbackAlt: string) {
  if (!copied) return "";
  return `<img src="images/${escapeHtml(copied.targetFileName)}" alt="${escapeHtml(planImage.caption || fallbackAlt)}" />`;
}

function buildCaption(page: Extract<PortfolioPlanPage, { type: "work_full_page" | "work_with_details" | "installation_spread" | "series_grid" }>) {
  return [page.title, page.year, page.medium, page.dimensions].filter((item) => item && !/unknown|n\/a|tbd/i.test(item)).join(", ");
}

function runVisualGate(input: PortfolioRenderInput & { htmlPath: string; pdfPath: string | null }) {
  const issues = [...input.preflightIssues];
  const pageCount = normalizedPages(input.plan).length;
  const externalText = fs.readFileSync(input.htmlPath, "utf8");
  const pdfSizeBytes = input.pdfPath && fs.existsSync(input.pdfPath) ? fs.statSync(input.pdfPath).size : 0;
  const maxPages = input.plan.maxPages;
  const targetFileSizeMb = input.plan.targetFileSizeMb;
  const workImagePages = input.plan.pages.filter((page) => page.type === "work_full_page" || page.type === "work_with_details" || page.type === "installation_spread" || page.type === "series_grid");

  if (!input.pdfPath) issues.push("Portfolio PDF was not rendered; visual gate cannot approve external submission.");
  if (forbiddenExternalPattern.test(externalText)) issues.push("Portfolio HTML contains forbidden external-facing terms.");
  if (maxPages && pageCount > maxPages) issues.push(`Portfolio has ${pageCount} pages, exceeding opportunity maxPages ${maxPages}.`);
  if (targetFileSizeMb && pdfSizeBytes > targetFileSizeMb * 1024 * 1024) issues.push(`Portfolio PDF is ${(pdfSizeBytes / 1024 / 1024).toFixed(2)} MB, exceeding target ${targetFileSizeMb} MB.`);
  if (input.webResearchReferences.length < 3) issues.push("Fewer than three portfolio design/application references were recorded.");
  if (workImagePages.length === 0) issues.push("Portfolio plan has no image-bearing work pages.");

  for (const copied of input.copiedImages) {
    if (copied.tooSmallForFullPage) issues.push(`Image may be too small for full-page use: ${copied.sourcePath} (${copied.width}x${copied.height}).`);
  }

  const domCheck = tryCheckHtmlLayout(input.htmlPath);
  issues.push(...domCheck.issues);

  return {
    checkedAt: new Date().toISOString(),
    method: "HTML rendered with Playwright when available; PDF existence, page count, file size, text, image asset, and DOM layout checks.",
    opportunityTitle: input.opportunity.title,
    pageCount,
    maxPages: maxPages || null,
    pdfPath: input.pdfPath,
    pdfSizeBytes,
    copiedImages: input.copiedImages,
    domCheck,
    issues,
    passed: issues.length === 0
  };
}

function tryCheckHtmlLayout(htmlPath: string) {
  try {
    const req = eval("require") as NodeRequire;
    req.resolve("playwright");
    const childProcess = req("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage({ viewport: { width: 794, height: 1123 } });
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          const result = await page.evaluate(() => {
            const issues = [];
            const pages = Array.from(document.querySelectorAll(".page"));
            pages.forEach((page, index) => {
              const rect = page.getBoundingClientRect();
              const images = Array.from(page.querySelectorAll("img"));
              if (images.length) {
                const visibleImages = images.filter((img) => {
                  const r = img.getBoundingClientRect();
                  return r.width >= 180 && r.height >= 160 && img.complete && img.naturalWidth > 0;
                });
                if (!visibleImages.length) issues.push(\`Page \${index + 1} has image tags but no clearly visible loaded image.\`);
              }
              const caption = page.querySelector(".caption");
              if (caption) {
                const fontSize = Number.parseFloat(getComputedStyle(caption).fontSize);
                if (fontSize < 8.5) issues.push(\`Page \${index + 1} caption font is below readable size.\`);
              }
              if (rect.height < 700) issues.push(\`Page \${index + 1} appears too short or mostly blank.\`);
            });
            return { pageCount: pages.length, issues };
          });
          console.log(JSON.stringify(result));
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    const output = childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      encoding: "utf8",
      timeout: 30000
    });
    return JSON.parse(output) as { pageCount: number; issues: string[] };
  } catch (error) {
    return { pageCount: 0, issues: [`Playwright DOM visual check unavailable: ${error instanceof Error ? error.message : "unknown error"}`] };
  }
}

function tryRenderPortfolioPdf(htmlPath: string, externalDir: string) {
  try {
    const req = eval("require") as NodeRequire;
    req.resolve("playwright");
    const pdfPath = path.join(externalDir, "portfolio.pdf");
    const childProcess = req("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage();
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          await page.pdf({ path: ${JSON.stringify(pdfPath)}, format: "A4", printBackground: true });
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      stdio: "ignore",
      timeout: 30000
    });
    return fs.existsSync(pdfPath) ? pdfPath : null;
  } catch {
    return null;
  }
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
