import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import type { Opportunity, PortfolioIssueClassification, PortfolioPlan, PortfolioPlanImage, PortfolioPlanPage, PortfolioVisualGateResult } from "@/types/domain";

const requireFromRenderer = createRequire(import.meta.url);

export type CopiedPortfolioImage = {
  sourcePath: string;
  targetFileName: string;
  width: number;
  height: number;
  format: string;
  sizeBytes: number;
  optimized: boolean;
  tooSmallForFullPage: boolean;
};

type PortfolioRenderInput = {
  externalDir: string;
  internalDir: string;
  opportunity: Opportunity;
  plan: PortfolioPlan;
  copiedImages: CopiedPortfolioImage[];
  webResearchReferences: string[];
  preflightIssues: string[];
  outputBaseName?: string;
};

const forbiddenExternalPattern = /\b(mock|test pdf|review committee|draft|placeholder|generated by ai|for this open call|selected for|ready-to-copy|unknown|n\/a|tbd|dimensions recorded in source material)\b/i;
const genericStatementPattern = /\b(explores the relationship|acts as a space|creates dialogue|questions boundaries|liminal|poetic resonance|embodied experience)\b/i;

export function renderPortfolioPackage(input: PortfolioRenderInput) {
  const outputBaseName = safeOutputBaseName(input.outputBaseName || "portfolio");
  const imageBySource = new Map(input.copiedImages.map((image) => [image.sourcePath, image]));
  const html = renderPortfolioHtml(input.plan, imageBySource);
  const htmlFileName = outputBaseName === "portfolio" ? "portfolio.html" : `${outputBaseName}.html`;
  const pdfFileName = outputBaseName === "portfolio" ? "portfolio.pdf" : `${outputBaseName}.pdf`;
  const reportFileName = outputBaseName === "portfolio" ? "portfolio-visual-check.json" : `portfolio-visual-check-${outputBaseName}.json`;
  const htmlPath = path.join(input.externalDir, htmlFileName);
  fs.writeFileSync(htmlPath, html, "utf8");

  const pdfPath = renderHtmlToPdf(htmlPath, path.join(input.externalDir, pdfFileName));
  const visualReport = runVisualGate({ ...input, htmlPath, pdfPath });
  fs.writeFileSync(path.join(input.internalDir, reportFileName), JSON.stringify(visualReport, null, 2), "utf8");
  return { htmlPath, pdfPath, visualReport };
}

function renderPortfolioHtml(plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>) {
  return `<!doctype html>
<html lang="${escapeHtml(plan.language || "en")}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(plan.artistName || "Artist")} - ${escapeHtml(plan.portfolioTitle || "Selected Works")}</title>
<style>
@page { size: A4; margin: 18mm; }
* { box-sizing: border-box; }
body { margin: 0; color: #191919; background: #fff; font-family: Arial, Helvetica, sans-serif; }
.page { width: 174mm; min-height: 261mm; break-after: page; display: flex; flex-direction: column; justify-content: center; gap: 8mm; }
.cover { justify-content: center; gap: 6mm; }
.cover h1 { margin: 0; font-size: 28px; line-height: 1.18; font-weight: 500; letter-spacing: 0; }
.cover .subtitle { margin: 0; font-size: 15px; line-height: 1.45; }
.cover .meta { margin: 0; font-size: 10.5px; line-height: 1.5; color: #4a4a4a; }
.statement { justify-content: center; }
.statement p { width: 135mm; margin: 0; font-size: 12px; line-height: 1.7; }
.work-title { margin: 0; font-size: 12px; line-height: 1.35; font-weight: 500; }
.work-image { display: block; width: 100%; max-height: 198mm; object-fit: contain; object-position: center; }
.caption-below .work-image { max-height: 188mm; }
.text-image { display: grid; grid-template-columns: 42mm 1fr; gap: 10mm; align-items: center; }
.text-image p.note { margin: 0; font-size: 10.5px; line-height: 1.55; color: #333; }
.two-image { display: grid; grid-template-columns: 1fr; gap: 6mm; }
.two-image img { width: 100%; max-height: 92mm; object-fit: contain; }
.detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.detail-grid img { width: 100%; max-height: 88mm; object-fit: contain; }
.series-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5mm; align-items: center; }
.series-grid-large { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 7mm; align-items: center; }
.series-grid-large img { width: 100%; max-height: 86mm; object-fit: contain; }
.series-grid img { width: 100%; max-height: 78mm; object-fit: contain; }
.installation-spread .primary { max-height: 135mm; }
.installation-spread .detail-grid img { max-height: 58mm; }
.caption { margin: 0; max-width: 150mm; font-size: 9.5px; line-height: 1.45; color: #2c2c2c; }
.list-page { justify-content: center; }
.list-page h2 { margin: 0 0 6mm; font-size: 14px; font-weight: 500; }
.list-page p, .list-page li { font-size: 10.5px; line-height: 1.55; }
.list-page ul { margin: 0; padding-left: 5mm; }
</style>
</head>
<body>
${normalizedPages(plan).map((page) => renderPage(page, plan, imageBySource)).join("\n")}
</body>
</html>
`;
}

function normalizedPages(plan: PortfolioPlan): PortfolioPlanPage[] {
  if (plan.pages.some((page) => page.type === "cover")) return plan.pages;
  return [
    {
      type: "cover",
      title: plan.artistName,
      subtitle: plan.portfolioTitle || "Selected Works",
      year: plan.year
    },
    ...plan.pages
  ];
}

function renderPage(page: PortfolioPlanPage, plan: PortfolioPlan, imageBySource: Map<string, CopiedPortfolioImage>) {
  if (page.type === "cover") {
    return `<section class="page cover">
  <h1>${escapeHtml(page.title || plan.artistName)}</h1>
  <p class="subtitle">${escapeHtml(page.subtitle || plan.portfolioTitle || "Selected Works")}</p>
  ${page.year || plan.year ? `<p class="meta">${escapeHtml(page.year || plan.year)}</p>` : ""}
  ${page.contact ? `<p class="meta">${escapeHtml(page.contact)}</p>` : ""}
</section>`;
  }

  if (page.type === "short_statement") {
    return `<section class="page statement"><p>${escapeHtml(page.text)}</p></section>`;
  }

  if (page.type === "project_opener") {
    return `<section class="page statement">
  <p class="work-title">${escapeHtml(page.title)}</p>
  <p>${escapeHtml(page.text || "")}</p>
</section>`;
  }

  if (page.type === "work_full_page" || page.type === "single_work_full_page") {
    const image = imageBySource.get(page.imagePath);
    return `<section class="page work-page">
  ${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "image_with_caption_below") {
    const image = imageBySource.get(page.images[0]?.path || "");
    return `<section class="page caption-below">
  ${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "text_left_image_right" || page.type === "text_image_context") {
    const image = imageBySource.get(page.images[0]?.path || "");
    return `<section class="page text-image">
  <p class="note">${escapeHtml(page.text || "")}</p>
  <div>${image ? `<img class="work-image" src="images/${escapeHtml(image.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}<p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p></div>
</section>`;
  }

  if (page.type === "two_image_detail_spread" || page.type === "two_image_spread") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied).slice(0, 2);
    return `<section class="page">
  <div class="two-image">${images.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "work_with_details" || page.type === "single_work_with_detail" || page.type === "installation_spread" || page.type === "installation_overview" || page.type === "installation_with_details") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied);
    const first = images[0];
    const rest = images.slice(1, 4);
    return `<section class="page ${page.type.includes("installation") ? "installation-spread" : "work-with-details"}">
  ${first?.copied ? `<img class="work-image primary" src="images/${escapeHtml(first.copied.targetFileName)}" alt="${escapeHtml(page.title)}" />` : ""}
  ${rest.length ? `<div class="detail-grid">${rest.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>` : ""}
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  if (page.type === "series_grid" || page.type === "series_grid_large" || page.type === "series_overview_grid" || page.type === "image_research_grid") {
    const images = page.images.map((item) => ({ plan: item, copied: imageBySource.get(item.path) })).filter((item) => item.copied).slice(0, page.type === "series_grid_large" ? 4 : 4);
    return `<section class="page series">
  <div class="${page.type === "series_grid_large" ? "series-grid-large" : "series-grid"}">${images.map((item) => renderImage(item.plan, item.copied, page.title)).join("")}</div>
  <p class="caption">${escapeHtml(page.caption || buildCaption(page))}</p>
</section>`;
  }

  const listPage = page as Extract<PortfolioPlanPage, { type: "contact" | "contact_page" | "selected_works_list" }>;
  const listItems = listPage.works?.length ? `<ul>${listPage.works.map((item: string) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>` : "";
  return `<section class="page list-page">
  ${listPage.title ? `<h2>${escapeHtml(listPage.title)}</h2>` : ""}
  ${listPage.text ? `<p>${escapeHtml(listPage.text)}</p>` : ""}
  ${listItems}
</section>`;
}

function renderImage(planImage: PortfolioPlanImage, copied: CopiedPortfolioImage | undefined, fallbackAlt: string) {
  if (!copied) return "";
  return `<img src="images/${escapeHtml(copied.targetFileName)}" alt="${escapeHtml(planImage.caption || fallbackAlt)}" />`;
}

function buildCaption(page: Extract<PortfolioPlanPage, { title: string; year?: string; medium?: string; dimensions?: string }>) {
  const year = "year" in page ? page.year : undefined;
  const medium = "medium" in page ? page.medium : undefined;
  const dimensions = "dimensions" in page ? page.dimensions : undefined;
  return [page.title, year, medium, dimensions].filter((item) => item && !/unknown|n\/a|tbd/i.test(item)).join(", ");
}

function runVisualGate(input: PortfolioRenderInput & { htmlPath: string; pdfPath: string | null }): PortfolioVisualGateResult {
  const autoFixableIssues: PortfolioIssueClassification[] = [];
  const blockingIssues: PortfolioIssueClassification[] = [];
  const warnings: PortfolioIssueClassification[] = [];
  const suggestedRepairs: string[] = [];
  const pageCount = normalizedPages(input.plan).length;
  const externalText = fs.readFileSync(input.htmlPath, "utf8");
  const pdfSizeBytes = input.pdfPath && fs.existsSync(input.pdfPath) ? fs.statSync(input.pdfPath).size : 0;
  const constraints = input.plan.portfolioConstraints || { targetPages: 20, minimumPages: 16, maximumPages: input.plan.maxPages || 24 };
  const maxPages = constraints.maximumPages || input.plan.maxPages;
  const targetFileSizeMb = input.plan.targetFileSizeMb;
  const workImagePages = input.plan.pages.filter((page) => page.type === "work_full_page" || page.type === "single_work_full_page" || "images" in page);

  for (const issue of input.preflightIssues) {
    if (/references no formal image paths|no structured|no image-bearing/i.test(issue)) blockingIssues.push(classify("no_usable_images", issue, "blocking"));
    else autoFixableIssues.push(classify("image_preflight", issue, "auto_fixable"));
  }
  if (!input.pdfPath) autoFixableIssues.push(classify("pdf_not_rendered", "Portfolio PDF was not rendered; retry or HTML remains available for inspection.", "auto_fixable"));
  if (forbiddenExternalPattern.test(externalText)) autoFixableIssues.push(classify("forbidden_terms", "Portfolio HTML contains forbidden external-facing terms.", "auto_fixable"));
  if (genericStatementPattern.test(externalText)) autoFixableIssues.push(classify("statement_too_generic", "Portfolio statement contains generic application-language phrasing.", "auto_fixable"));
  if (pageCount < constraints.minimumPages) autoFixableIssues.push(classify("page_count_too_low", `Portfolio has ${pageCount} pages, below minimum ${constraints.minimumPages}.`, "auto_fixable"));
  if (maxPages && pageCount > maxPages) autoFixableIssues.push(classify("page_count_too_high", `Portfolio has ${pageCount} pages, exceeding maximum ${maxPages}.`, "auto_fixable"));
  if (targetFileSizeMb && pdfSizeBytes > targetFileSizeMb * 1024 * 1024) autoFixableIssues.push(classify("pdf_too_large", `Portfolio PDF is ${(pdfSizeBytes / 1024 / 1024).toFixed(2)} MB, exceeding target ${targetFileSizeMb} MB.`, "auto_fixable"));
  if (input.webResearchReferences.length < 3) warnings.push(classify("limited_references", "Fewer than three portfolio design/application references were recorded.", "warning"));
  if (workImagePages.length === 0) blockingIssues.push(classify("no_usable_images", "Portfolio plan has no image-bearing work pages.", "blocking"));
  if (!input.plan.layoutResearchUsed || input.plan.layoutResearchUsed.derivedPrinciples.length < 5) autoFixableIssues.push(classify("portfolio_research_missing", "Portfolio layout research is missing or too thin.", "auto_fixable"));
  if (!input.plan.layoutResearchUsed || input.plan.layoutResearchUsed.appliedPrinciples.length === 0) autoFixableIssues.push(classify("portfolio_research_not_applied", "Portfolio layout research was recorded but not applied to PortfolioPlan.", "auto_fixable"));
  if (!input.plan.curatorialSummary?.passedDiversityGate) {
    const availableSingleSeries = input.plan.curatorialSummary?.projectGroupCount <= 1 && input.plan.portfolioTitle !== "Selected Works";
    if (!availableSingleSeries) autoFixableIssues.push(classify("curatorial_gate_failed", "Portfolio did not pass project diversity, page rhythm, or layout strategy checks.", "auto_fixable"));
  }

  for (const copied of input.copiedImages) {
    if (copied.tooSmallForFullPage) autoFixableIssues.push({ ...classify("small_full_page_image", `Image may be too small for full-page use: ${copied.sourcePath} (${copied.width}x${copied.height}).`, "auto_fixable"), sourcePath: copied.sourcePath });
  }
  const plannedImagePaths = input.plan.pages.flatMap((page) => {
    if (page.type === "work_full_page" || page.type === "single_work_full_page") return [page.imagePath];
    if ("images" in page) return page.images.map((image) => image.path);
    return [];
  }).filter(Boolean);
  const duplicateImages = plannedImagePaths.filter((imagePath, index) => plannedImagePaths.indexOf(imagePath) !== index);
  if (duplicateImages.length) autoFixableIssues.push(classify("duplicate_images", `Portfolio repeats ${new Set(duplicateImages).size} image file(s).`, "auto_fixable"));
  for (const page of input.plan.pages) {
    if ("caption" in page && page.caption && page.caption.split(/\s+/).filter(Boolean).length > 35) autoFixableIssues.push(classify("caption_too_long", `Caption is longer than 35 words on page ${input.plan.pages.indexOf(page) + 1}.`, "auto_fixable"));
    if ((page.type === "series_grid" || page.type === "series_grid_large" || page.type === "series_overview_grid" || page.type === "image_research_grid") && page.images.length > 4) autoFixableIssues.push(classify("series_grid_too_dense", `Series grid has ${page.images.length} images and should be split into larger pages.`, "auto_fixable"));
  }
  const strategies = input.plan.pages.map((page) => page.layoutStrategy || page.type);
  if (new Set(strategies).size < 3) autoFixableIssues.push(classify("layout_strategy_diversity_too_low", "Portfolio uses fewer than three layout strategies.", "auto_fixable"));
  if (hasConsecutiveStrategy(strategies, "single_work_full_page", 4) || hasConsecutiveStrategy(strategies, "work_full_page", 4)) autoFixableIssues.push(classify("too_many_consecutive_full_page_works", "More than four consecutive pages use single-work full-page layout.", "auto_fixable"));

  const domCheck = tryCheckHtmlLayout(input.htmlPath);
  for (const issue of domCheck.issues) autoFixableIssues.push(classify(issue.includes("caption") ? "caption_too_small" : "layout_balance", issue, "auto_fixable"));
  suggestedRepairs.push(...autoFixableIssues.map((issue) => repairSuggestion(issue.code)));

  return {
    checkedAt: new Date().toISOString(),
    method: "HTML rendered with Playwright when available; PDF existence, page count, file size, text, image asset, and DOM layout checks.",
    opportunityTitle: input.opportunity.title,
    pageCount,
    targetPages: constraints.targetPages,
    minimumPages: constraints.minimumPages,
    maximumPages: constraints.maximumPages,
    pdfPath: input.pdfPath,
    pdfSizeBytes,
    autoFixableIssues,
    blockingIssues,
    warnings,
    suggestedRepairs,
    copiedImages: input.copiedImages,
    domCheck,
    passed: blockingIssues.length === 0 && autoFixableIssues.length === 0
  };
}

function classify(code: string, message: string, severity: PortfolioIssueClassification["severity"]): PortfolioIssueClassification {
  return { code, message, severity };
}

function repairSuggestion(code: string) {
  const suggestions: Record<string, string> = {
    page_count_too_low: "Add detail, context, installation, or selected-works-list pages.",
    page_count_too_high: "Remove secondary detail pages or merge minor works.",
    forbidden_terms: "Rewrite captions/statement without internal or placeholder words.",
    small_full_page_image: "Move image to detail layout or use an alternate higher-resolution file.",
    pdf_too_large: "Optimize images and rerender PDF.",
    caption_too_small: "Increase caption size or reduce caption length.",
    caption_too_long: "Compress the caption to a formal 20-35 word maximum.",
    statement_too_generic: "Rewrite the statement with concrete materials, image sources, making methods, and display context.",
    series_grid_too_dense: "Split dense grids into overview and detail pages.",
    duplicate_images: "Remove duplicate image uses or assign them to distinct detail/context roles.",
    layout_balance: "Rebalance page layout and rerender.",
    curatorial_gate_failed: "Regroup works by project, vary page roles, and rerender.",
    portfolio_research_missing: "Run portfolio layout research and record principles before planning.",
    portfolio_research_not_applied: "Apply research principles to project grouping, page rhythm, captions, and selected works list.",
    layout_strategy_diversity_too_low: "Introduce opener, grid, detail, installation/context, list, and contact pages.",
    too_many_consecutive_full_page_works: "Convert repeated full-page images into grids, spreads, or context pages."
  };
  return suggestions[code] || "Automatically adjust PortfolioPlan and rerender.";
}

function hasConsecutiveStrategy(strategies: string[], strategy: string, maxRun: number) {
  let run = 0;
  for (const item of strategies) {
    if (item === strategy) {
      run += 1;
      if (run > maxRun) return true;
    } else {
      run = 0;
    }
  }
  return false;
}

function tryCheckHtmlLayout(htmlPath: string) {
  try {
    requireFromRenderer.resolve("playwright");
    const childProcess = requireFromRenderer("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage({ viewport: { width: 794, height: 1123 } });
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          const result = await page.evaluate(() => {
            const issues = [];
            const pages = Array.from(document.querySelectorAll(".page"));
            pages.forEach((page, index) => {
              const rect = page.getBoundingClientRect();
              const images = Array.from(page.querySelectorAll("img"));
              if (images.length) {
                const visibleImages = images.filter((img) => {
                  const r = img.getBoundingClientRect();
                  return r.width >= 180 && r.height >= 160 && img.complete && img.naturalWidth > 0;
                });
                if (!visibleImages.length) issues.push(\`Page \${index + 1} has image tags but no clearly visible loaded image.\`);
              }
              const caption = page.querySelector(".caption");
              if (caption) {
                const fontSize = Number.parseFloat(getComputedStyle(caption).fontSize);
                if (fontSize < 8.5) issues.push(\`Page \${index + 1} caption font is below readable size.\`);
              }
              if (rect.height < 700) issues.push(\`Page \${index + 1} appears too short or mostly blank.\`);
            });
            return { pageCount: pages.length, issues };
          });
          console.log(JSON.stringify(result));
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    const output = childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      encoding: "utf8",
      timeout: 30000
    });
    return JSON.parse(output) as { pageCount: number; issues: string[] };
  } catch (error) {
    return { pageCount: 0, issues: [`Playwright DOM visual check unavailable: ${error instanceof Error ? error.message : "unknown error"}`] };
  }
}

export function renderHtmlToPdf(htmlPath: string, pdfPath: string) {
  try {
    requireFromRenderer.resolve("playwright");
    const childProcess = requireFromRenderer("node:child_process") as typeof import("node:child_process");
    const code = `
      const { chromium } = require("playwright");
      (async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const page = await browser.newPage();
          await page.goto(${JSON.stringify(`file://${htmlPath}`)}, { waitUntil: "networkidle" });
          await page.pdf({ path: ${JSON.stringify(pdfPath)}, format: "A4", printBackground: true });
        } finally {
          await browser.close();
        }
      })().catch((error) => { console.error(error); process.exit(1); });
    `;
    childProcess.execFileSync(process.execPath, ["-e", code], {
      cwd: process.cwd(),
      stdio: "ignore",
      timeout: 30000
    });
    return fs.existsSync(pdfPath) ? pdfPath : null;
  } catch {
    return renderFallbackPdfFromHtml(htmlPath, pdfPath);
  }
}

function safeOutputBaseName(value: string) {
  return value.replace(/[^a-z0-9-]+/gi, "-").replace(/^-+|-+$/g, "") || "portfolio";
}

function renderFallbackPdfFromHtml(htmlPath: string, pdfPath: string) {
  try {
    const html = fs.existsSync(htmlPath) ? fs.readFileSync(htmlPath, "utf8") : "";
    const title = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g, " ").trim() || "Portfolio";
    const pageTexts = Array.from(html.matchAll(/<section[^>]*class="[^"]*\bpage\b[^"]*"[^>]*>([\s\S]*?)<\/section>/gi))
      .map((match) => htmlToPlainText(match[1]))
      .filter(Boolean);
    writeSimplePdf(pdfPath, title, pageTexts.length ? pageTexts : [htmlToPlainText(html) || title]);
    return fs.existsSync(pdfPath) ? pdfPath : null;
  } catch {
    return null;
  }
}

function htmlToPlainText(html: string) {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<img\b[^>]*alt="([^"]*)"[^>]*>/gi, " $1 ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|h1|h2|li|pre|div)>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

function writeSimplePdf(pdfPath: string, title: string, pageTexts: string[]) {
  const objects: string[] = [];
  const addObject = (body: string) => {
    objects.push(body);
    return objects.length;
  };
  const catalogId = addObject("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = addObject("__PAGES__");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds: number[] = [];

  for (const [index, text] of pageTexts.entries()) {
    const content = buildPdfPageContent(index === 0 ? `${title}\n\n${text}` : text);
    const contentId = addObject(`<< /Length ${Buffer.byteLength(content, "binary")} >>\nstream\n${content}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  }
  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;
  objects[catalogId - 1] = "<< /Type /Catalog /Pages 2 0 R >>";

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(pdf, "binary"));
    pdf += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, "binary");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  fs.writeFileSync(pdfPath, pdf, "binary");
}

function buildPdfPageContent(text: string) {
  const lines = wrapPdfText(text, 86).slice(0, 44);
  const commands = ["BT", "/F1 10 Tf", "50 790 Td", "14 TL"];
  for (const line of lines) commands.push(`(${escapePdfText(line)}) Tj`, "T*");
  commands.push("ET");
  return commands.join("\n");
}

function wrapPdfText(text: string, width: number) {
  const words = text.replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?").split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > width) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
