import type { PortfolioPlan, PortfolioSourceAudit, SourceMaterial } from "@/types/domain";
import { findAiCliches } from "./languageReviewCheck";

export type PortfolioQualityInput = {
  portfolioText: string;
  selectedWorks: string;
  portfolioPlan?: PortfolioPlan;
  portfolioSourceAudit?: PortfolioSourceAudit;
  materialSources: Pick<SourceMaterial, "kind" | "title" | "fileName" | "filePath" | "content" | "analysis">[];
  webResearchReferences: string[];
};

export function checkPortfolioPreparation(input: PortfolioQualityInput) {
  const issues: string[] = [];
  const existingPortfolioSources = input.portfolioSourceAudit?.existingPortfolioSources.length
    ? input.portfolioSourceAudit.existingPortfolioSources
    : input.materialSources.filter((source) => source.kind === "portfolio").map((source) => source.fileName || source.title || source.filePath).filter(Boolean);
  if (existingPortfolioSources.length === 0) {
    issues.push("No existing portfolio source was found; portfolio generation must inspect user-provided portfolio material before producing a final portfolio.");
  }
  if (input.webResearchReferences.length < 3) {
    issues.push("Portfolio generation needs at least three web/design research references recorded before final layout.");
  }
  return {
    ok: issues.length === 0,
    issues,
    existingPortfolioSources
  };
}

export function checkPortfolioOutput(input: Pick<PortfolioQualityInput, "portfolioText" | "selectedWorks" | "portfolioPlan">) {
  const issues: string[] = [];
  const cliches = findAiCliches(input.portfolioText);
  const captions = input.portfolioText.split(/\r?\n/).filter((line) => /[,，].*\b(19|20)\d{2}\b/.test(line));
  const selectedWorkLines = input.selectedWorks.split(/\r?\n/).filter((line) => line.trim().length > 0);
  const selectedImageLines = selectedWorkLines.filter((line) => /Image:\s*\S+/i.test(line));
  const planImageCount = input.portfolioPlan ? countPortfolioPlanImages(input.portfolioPlan) : 0;
  const forbiddenPlanText = input.portfolioPlan ? JSON.stringify(input.portfolioPlan) : "";

  if (!input.portfolioPlan) {
    issues.push("Portfolio has no structured PortfolioPlan; renderer must not depend on selectedWorks free text.");
  }
  if (input.portfolioPlan && input.portfolioPlan.pages.length === 0) {
    issues.push("PortfolioPlan has no pages.");
  }
  if (!input.portfolioPlan && selectedWorkLines.length === 0) {
    issues.push("Portfolio has no selected works; AI must select works before producing a submission portfolio.");
  }
  if (planImageCount === 0 && selectedImageLines.length === 0) {
    issues.push("Portfolio has no selected image paths; visual layout and file-size checks cannot be completed.");
  }
  if (!input.portfolioPlan && selectedWorkLines.length > 0 && captions.length < Math.min(3, selectedWorkLines.length)) {
    issues.push("Portfolio text does not show enough caption-like lines with title, date, medium/dimensions rhythm.");
  }
  if (/\b(mock|review committee|draft|placeholder|generated by ai|for this open call|selected for|ready-to-copy|unknown|n\/a|tbd|dimensions recorded in source material)\b/i.test(forbiddenPlanText)) {
    issues.push("PortfolioPlan contains forbidden external-facing language or missing-data placeholders.");
  }
  if (input.portfolioText.length > 0 && input.portfolioText.split(/\s+/).length / Math.max(1, selectedWorkLines.length) > 180) {
    issues.push("Portfolio text is too dense for an application portfolio; reduce captions and keep images primary.");
  }
  if (cliches.length > 0) {
    issues.push(`Portfolio statement has AI-like abstract phrases: ${cliches.join(", ")}`);
  }

  return { ok: issues.length === 0, issues };
}

function countPortfolioPlanImages(plan: PortfolioPlan) {
  return plan.pages.reduce((count, page) => {
    if (page.type === "work_full_page") return count + (page.imagePath ? 1 : 0);
    if (page.type === "work_with_details" || page.type === "installation_spread" || page.type === "series_grid") return count + page.images.filter((image) => image.path).length;
    return count;
  }, 0);
}
