import type { PortfolioPlan, PortfolioSourceAudit, SourceMaterial } from "@/types/domain";
import { findAiCliches } from "./languageReviewCheck";

export type PortfolioQualityInput = {
  portfolioText: string;
  selectedWorks: string;
  portfolioPlan?: PortfolioPlan;
  portfolioSourceAudit?: PortfolioSourceAudit;
  materialSources: Pick<SourceMaterial, "kind" | "title" | "fileName" | "filePath" | "content" | "analysis">[];
  webResearchReferences: string[];
};

export function checkPortfolioPreparation(input: PortfolioQualityInput) {
  const issues: string[] = [];
  const warnings: string[] = [];
  const existingPortfolioSources = input.portfolioSourceAudit?.existingPortfolioSources.length
    ? input.portfolioSourceAudit.existingPortfolioSources
    : input.materialSources.filter((source) => source.kind === "portfolio").map((source) => source.fileName || source.title || source.filePath).filter(Boolean);
  if (existingPortfolioSources.length === 0) {
    warnings.push("No existing portfolio source was found; the system should rely on works records and available image files, and record this source gap internally.");
  }
  if (input.webResearchReferences.length < 3) {
    warnings.push("Portfolio generation has fewer than three web/design research references recorded; this is an internal quality warning, not a user-blocking issue.");
  }
  return {
    ok: issues.length === 0,
    issues,
    warnings,
    existingPortfolioSources
  };
}

export function checkPortfolioOutput(input: Pick<PortfolioQualityInput, "portfolioText" | "selectedWorks" | "portfolioPlan" | "portfolioSourceAudit">) {
  const issues: string[] = [];
  const warnings: string[] = [];
  const cliches = findAiCliches(input.portfolioText);
  const captions = input.portfolioText.split(/\r?\n/).filter((line) => /[,，].*\b(19|20)\d{2}\b/.test(line));
  const selectedWorkLines = input.selectedWorks.split(/\r?\n/).filter((line) => line.trim().length > 0);
  const selectedImageLines = selectedWorkLines.filter((line) => /Image:\s*\S+/i.test(line));
  const planImageCount = input.portfolioPlan ? countPortfolioPlanImages(input.portfolioPlan) : 0;
  const forbiddenPlanText = input.portfolioPlan ? JSON.stringify(input.portfolioPlan) : "";

  if (!input.portfolioPlan) {
    issues.push("Portfolio has no structured PortfolioPlan; renderer must not depend on selectedWorks free text.");
  }
  if (input.portfolioPlan && input.portfolioPlan.pages.length === 0) {
    issues.push("PortfolioPlan has no pages.");
  }
  if (!input.portfolioPlan && selectedWorkLines.length === 0) {
    issues.push("Portfolio has no selected works; AI must select works before producing a submission portfolio.");
  }
  if (planImageCount === 0 && selectedImageLines.length === 0) {
    issues.push("Portfolio has no selected image paths; visual layout and file-size checks cannot be completed.");
  }
  if (!input.portfolioPlan && selectedWorkLines.length > 0 && captions.length < Math.min(3, selectedWorkLines.length)) {
    issues.push("Portfolio text does not show enough caption-like lines with title, date, medium/dimensions rhythm.");
  }
  if (/\b(ai generated|preview|test|mock|debug|review committee|draft|placeholder|generated by ai|for this open call|selected for|ready-to-copy|unknown|n\/a|tbd|dimensions recorded in source material)\b/i.test(forbiddenPlanText)) {
    warnings.push("PortfolioPlan contains forbidden external-facing language or missing-data placeholders; visual gate should auto-rewrite before final output.");
  }
  if (input.portfolioText.length > 0 && input.portfolioText.split(/\s+/).length / Math.max(1, selectedWorkLines.length) > 180) {
    warnings.push("Portfolio text is too dense for an application portfolio; auto-repair should reduce captions and keep images primary.");
  }
  if (cliches.length > 0) {
    warnings.push(`Portfolio statement has AI-like abstract phrases: ${cliches.join(", ")}; auto-repair should rewrite with concrete materials and display context.`);
  }
  const mandatoryImageIssues = checkMandatoryPortfolioImageSelection(input.portfolioPlan, input.portfolioSourceAudit);
  issues.push(...mandatoryImageIssues);

  return { ok: issues.length === 0, issues, warnings };
}

function checkMandatoryPortfolioImageSelection(plan?: PortfolioPlan, audit?: PortfolioSourceAudit) {
  if (!plan) return [];
  const issues: string[] = [];
  const supportOnlyPaths = new Set((audit?.supportOnlyImages || []).map((image) => image.path));
  const analysisByPath = new Map((audit?.imageAnalyses || []).map((analysis) => [analysis.path, analysis]));
  const isSupportOnly = (imagePath: string, role?: string) => {
    const analysis = analysisByPath.get(imagePath);
    return supportOnlyPaths.has(imagePath)
      || Boolean(analysis?.supportOnly || analysis?.cropRisk || analysis?.partialImageRisk || analysis?.temporaryPhotoRisk)
      || /detail|installation_view|process|archive_reference|temporary|cropped|partial|weak_candidate|excluded/.test(role || "")
      || /detail|closeup|close-up|crop|cropped|process|install|installation|studio|temp|temporary|screenshot|screen|archive|reference|packing|backup|partial/i.test(imagePath.split(/[\\/]/).pop() || imagePath);
  };
  plan.pages.forEach((page, index) => {
    if (page.type === "work_full_page" || page.type === "single_work_full_page") {
      if (isSupportOnly(page.imagePath, page.imageRole)) issues.push(`Portfolio mandatory image gate failed: primary page uses incomplete/support-only image on page ${index + 1}: ${page.imagePath}`);
    }
    if ("images" in page) {
      const lead = page.images[0];
      if (lead && (page.pageRole === "overview" || page.pageRole === "primary_work" || /overview|primary/.test(page.layoutStrategy || page.type)) && isSupportOnly(lead.path, lead.role)) {
        issues.push(`Portfolio mandatory image gate failed: support-only image used as primary/overview lead on page ${index + 1}: ${lead.path}`);
      }
    }
  });
  for (const group of audit?.projectGroupPrimaryImages || []) {
    if (group.completeImageAvailable && !group.primaryImagePath) {
      issues.push(`Portfolio mandatory image gate failed: complete image exists but was not selected as primary for ${group.projectGroup}.`);
    }
    if (!group.completeImageAvailable && group.qualityBlocked) {
      issues.push(`Portfolio mandatory image gate failed: no complete artwork image exists for ${group.projectGroup}; package must remain quality_blocked unless context-only material is explicitly accepted.`);
    }
  }
  const listedWorks = plan.pages.flatMap((page) => page.type === "selected_works_list" ? page.works || [] : []);
  const representedTitles = new Set((audit?.selectedImages || [])
    .filter((image) => image.use === "primary" || image.use === "overview")
    .filter((image) => !isSupportOnly(image.path, image.assignedRole))
    .map((image) => normalizeForListMatch(image.title || "")));
  if (listedWorks.length >= 6 && representedTitles.size > 0) {
    const unrepresented = listedWorks.filter((work) => ![...representedTitles].some((title) => normalizeForListMatch(work).includes(title) || title.includes(normalizeForListMatch(work).slice(0, 18))));
    if (unrepresented.length / listedWorks.length > 0.35) issues.push("Portfolio mandatory image gate failed: selected works list contains many works not visually represented by complete artwork images.");
  }
  return issues;
}

function normalizeForListMatch(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]+/gi, " ").trim();
}

function countPortfolioPlanImages(plan: PortfolioPlan) {
  return plan.pages.reduce((count, page) => {
    if (page.type === "work_full_page" || page.type === "single_work_full_page") return count + (page.imagePath ? 1 : 0);
    if ("images" in page) return count + page.images.filter((image) => image.path).length;
    return count;
  }, 0);
}
