import fs from "node:fs";
import path from "node:path";
import { callChatCompletion, getAiConfig } from "./aiProvider";
import { createApplication, readArtistData, recordPackageManifest, upsertOpportunity } from "./db";
import { refreshOpportunityPages } from "./opportunityPages";
import { generatedReportsDir } from "./paths";
import { writeApplicationPackage } from "./package";
import { asListText, extractJsonObject } from "./json";
import type { Opportunity } from "@/types/domain";

type AiApplicationPackage = {
  opportunityId?: number;
  draftZh?: string;
  draftEn?: string;
  checklist?: string | string[];
  selectedWorks?: string | string[];
  bioZh?: string;
  bioEn?: string;
  statementZh?: string;
  statementEn?: string;
  cvText?: string;
};

type AiAutomationResponse = {
  summaryZh?: string;
  summaryEn?: string;
  profileNotesZh?: string;
  profileNotesEn?: string;
  verifiedOpportunities?: {
    opportunityId?: number;
    title?: string;
    organization?: string;
    deadline?: string;
    location?: string;
    fee?: string;
    funding?: string;
    eligibility?: string;
    materials?: string;
    submissionMethod?: "email" | "web_form" | "unknown";
    summary?: string;
    score?: number;
    risks?: string;
    status?: "new" | "confirmed" | "preparing" | "ready_to_submit" | "submitted" | "waiting" | "shortlisted" | "rejected";
  }[];
  opportunityResearchPlanZh?: string[];
  opportunityResearchPlanEn?: string[];
  warnings?: string[];
  applicationPackages?: AiApplicationPackage[];
};

export async function runProjectAutomation() {
  if (!getAiConfig()) {
    throw new Error("External model automation is not configured. Add DEEPSEEK_API_KEY or ARTIST_STUDIO_AI_API_KEY to .env.local and restart the project.");
  }

  fs.mkdirSync(generatedReportsDir, { recursive: true });
  const initialData = readArtistData({
    materialLimit: 80,
    materialContentLimit: 3000,
    opportunityLimit: 120,
    opportunityRawContentLimit: 1500,
    applicationLimit: 20
  });
  const pageFetches = await refreshOpportunityPages(initialData.opportunities);
  const data = readArtistData({
    materialLimit: 80,
    materialContentLimit: 3000,
    opportunityLimit: 120,
    opportunityRawContentLimit: 6000,
    applicationLimit: 20
  });

  const prompt = buildAutomationPrompt(data);
  const ai = await callChatCompletion([
    {
      role: "system",
      content: [
        "You are an artist application automation assistant embedded in a Next.js project workspace.",
        "Return one strict JSON object only. Do not wrap it in markdown.",
        "Do not claim to have verified live deadlines, fees, or eligibility unless the provided source material contains that fact.",
        "Create applicationPackages only for opportunities already present in currentOpportunities by id."
      ].join("\n")
    },
    { role: "user", content: prompt }
  ]);

  const parsed = extractJsonObject(ai.content) as AiAutomationResponse;
  const opportunityById = new Map(data.opportunities.map((item: Opportunity) => [item.id, item]));
  const packagePaths: string[] = [];

  for (const verified of parsed.verifiedOpportunities ?? []) {
    const opportunity = typeof verified.opportunityId === "number" ? opportunityById.get(verified.opportunityId) : null;
    if (!opportunity) continue;
    const patch = verifiedOpportunityPatch(verified);
    const score = typeof patch.score === "number" ? Math.max(0, Math.min(100, Math.trunc(patch.score))) : undefined;
    upsertVerifiedOpportunity(opportunity, { ...patch, score });
  }

  for (const app of parsed.applicationPackages ?? []) {
    const opportunity = typeof app.opportunityId === "number" ? opportunityById.get(app.opportunityId) : null;
    if (!opportunity) continue;
    const draft = {
      draftZh: app.draftZh ?? "",
      draftEn: app.draftEn ?? "",
      checklist: asListText(app.checklist),
      selectedWorks: asListText(app.selectedWorks),
      bioZh: app.bioZh,
      bioEn: app.bioEn,
      statementZh: app.statementZh,
      statementEn: app.statementEn,
      cvText: app.cvText
    };
    const packagePath = writeApplicationPackage(opportunity, draft);
    const applicationId = createApplication({
      opportunityId: opportunity.id,
      draftZh: draft.draftZh,
      draftEn: draft.draftEn,
      checklist: draft.checklist,
      selectedWorks: draft.selectedWorks,
      packagePath,
      submissionLog: "Generated by project external-model automation. User approval is still required before submission."
    });
    recordPackageManifest({
      applicationId,
      opportunityId: opportunity.id,
      packagePath,
      manifestPath: path.join(packagePath, "package-manifest.json"),
      manifestVersion: 1,
      status: "draft"
    });
    packagePaths.push(packagePath);
  }

  const runStamp = new Date().toISOString().replace(/[:.]/g, "-");
  const reportPath = path.join(generatedReportsDir, `${runStamp}-project-ai-automation.md`);
  fs.writeFileSync(reportPath, renderReport(parsed, ai.provider, ai.model, packagePaths, pageFetches), "utf8");

  return {
    provider: ai.provider,
    model: ai.model,
    reportPath,
    packagePaths,
    data: readArtistData()
  };
}

function buildAutomationPrompt(data: ReturnType<typeof readArtistData>) {
  return JSON.stringify({
    task: "Use the current artist workspace to produce a project automation run. Summarize profile/material gaps, produce bilingual next steps, and draft packages for existing opportunities only when enough information exists.",
    outputSchema: {
      summaryZh: "Chinese summary for user review",
      summaryEn: "English summary",
      profileNotesZh: "Chinese profile/material notes",
      profileNotesEn: "English profile/material notes",
      opportunityResearchPlanZh: ["Chinese research/check plan; mark items requiring live verification"],
      opportunityResearchPlanEn: ["English research/check plan"],
      warnings: ["risks, missing data, or things requiring Codex/live verification"],
      verifiedOpportunities: [{
        opportunityId: "number from currentOpportunities only",
        title: "verified title from source page",
        organization: "verified organizer",
        deadline: "verified deadline with timezone if visible",
        fee: "application/participation/program fee details",
        funding: "stipend, travel, lodging, production budget, etc.",
        eligibility: "who can apply, especially China/international eligibility",
        materials: "required materials",
        submissionMethod: "email | web_form | unknown",
        summary: "bilingual-friendly concise summary",
        score: "0-100",
        risks: "unclear facts, fees, eligibility gaps, login/captcha/payment needs",
        status: "new | confirmed | rejected"
      }],
      applicationPackages: [{
        opportunityId: "number from currentOpportunities only",
        draftZh: "Chinese review draft",
        draftEn: "English draft or final-language draft if appropriate",
        checklist: ["required files, missing fields, approval checks"],
        selectedWorks: ["work title and image path if available"],
        bioZh: "optional Chinese bio",
        bioEn: "optional English bio",
        statementZh: "optional Chinese statement",
        statementEn: "optional English statement",
        cvText: "optional CV text"
      }]
    },
    rules: {
      reviewMaterialsMustBeBilingual: true,
      finalSubmissionLanguageDependsOnOpportunity: true,
      doNotSubmitWithoutUserApproval: true,
      doNotInventLiveOpportunityFacts: true,
      projectMayFetchUserProvidedLinks: true,
      externalApiMustUseFetchedSourceTextForVerification: true,
      externalApiCanDraftButCodexAutomationCanStillVerifyHighRiskFacts: true,
      applicationRegionDefaultsToWorldwide: true,
      selectedApplicationRegionMustGuideSearchAndRanking: true,
      maximumOpportunitiesPerRun: data.profile.automationBatchLimit,
      submissionApprovalMode: data.profile.submissionApprovalMode,
      opportunityFeePreference: data.profile.opportunityFeePreference,
      opportunityTierPreference: data.profile.opportunityTierPreference,
      opportunityFeePreferenceRule: "conservative prefers free or strongly funded opportunities and rejects pay-to-show economics; application_fee_ok allows modest application fees but still rejects booth, wall, venue, mandatory production, lodging, or high participation fees unless explicitly justified; paid_ok allows paid exhibitions/residencies to be considered only when clearly labeled with cost and risk, and payment still requires user confirmation.",
      opportunityTierPreferenceRule: "high_tier prioritizes museums, universities, foundations, respected residencies, credible nonprofits, and serious open calls; balanced includes high-tier and credible mid-tier opportunities; open also considers small spaces, new organizations, and experimental projects while scoring credibility and risk explicitly.",
      directApplyModeStopsForPaymentLoginCaptchaSensitiveAuthOrUnclearEligibility: true,
      multimodalMaterialsMustUseOriginalContentWhenProviderSupportsIt: true,
      extractedTextAndMetadataAreIndexingAidsOnly: true
    },
    profile: data.profile,
    works: data.works,
    cv: data.cv,
    materialSources: data.materialSources.map((source) => ({
      id: source.id,
      kind: source.kind,
      title: source.title,
      fileName: source.fileName,
      filePath: source.filePath,
      mimeType: source.mimeType,
      contentExcerpt: source.content
    })),
    currentOpportunities: data.opportunities
  }, null, 2);
}

function upsertVerifiedOpportunity(
  opportunity: Opportunity,
  patch: Omit<NonNullable<AiAutomationResponse["verifiedOpportunities"]>[number], "opportunityId">
) {
  upsertOpportunity({
    ...opportunity,
    ...withoutUndefined(patch),
    url: opportunity.url,
    source: opportunity.source || "project-ai-verified"
  });
}

function verifiedOpportunityPatch(verified: NonNullable<AiAutomationResponse["verifiedOpportunities"]>[number]) {
  return {
    title: verified.title,
    organization: verified.organization,
    deadline: verified.deadline,
    location: verified.location,
    fee: verified.fee,
    funding: verified.funding,
    eligibility: verified.eligibility,
    materials: verified.materials,
    submissionMethod: verified.submissionMethod,
    summary: verified.summary,
    score: verified.score,
    risks: verified.risks,
    status: verified.status
  };
}

function withoutUndefined<T extends Record<string, unknown>>(value: T) {
  return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as Partial<T>;
}

function renderReport(
  parsed: AiAutomationResponse,
  provider: string,
  model: string,
  packagePaths: string[],
  pageFetches: Awaited<ReturnType<typeof refreshOpportunityPages>>
) {
  return [
    "# Project AI Automation Run",
    "",
    `Provider: ${provider}`,
    `Model: ${model}`,
    `Generated at: ${new Date().toISOString()}`,
    "",
    "## 中文摘要",
    parsed.summaryZh ?? "",
    "",
    "## English Summary",
    parsed.summaryEn ?? "",
    "",
    "## 资料备注",
    parsed.profileNotesZh ?? "",
    "",
    "## Profile Notes",
    parsed.profileNotesEn ?? "",
    "",
    "## 机会核验计划",
    asListText(parsed.opportunityResearchPlanZh),
    "",
    "## Opportunity Verification Plan",
    asListText(parsed.opportunityResearchPlanEn),
    "",
    "## Warnings",
    asListText(parsed.warnings),
    "",
    "## Fetched Opportunity Pages",
    pageFetches.length
      ? pageFetches.map((item) => `- ${item.ok ? "OK" : "FAILED"} ${item.url}${item.error ? ` (${item.error})` : ""}`).join("\n")
      : "No user-provided opportunity pages fetched in this run.",
    "",
    "## Verified Opportunities",
    asListText(parsed.verifiedOpportunities),
    "",
    "## Generated Packages",
    packagePaths.length ? packagePaths.map((item) => `- ${item}`).join("\n") : "No application packages generated in this run."
  ].join("\n");
}
