import assert from "node:assert/strict";
import fs from "node:fs";
import { test } from "node:test";

const readText = (filePath) => fs.readFileSync(filePath, "utf8");

test("automation rules enforce two review nodes and file boundaries", () => {
  const rules = readText("src/lib/automationRules.ts");
  const finalReviewRoute = readText("src/app/api/applications/[id]/route.ts");
  const studioPanels = readText("src/app/components/StudioPanels.tsx");

  for (const snippet of [
    "choose_opportunities",
    "approve_final_submission_package",
    "internal-notes",
    "user-review",
    "external-submission",
    "testAndMockRunsMustBeIsolated",
    "portfolioMustUseExistingPortfolioAndWebResearch"
  ]) {
    assert.ok(rules.includes(snippet), `automation rules missing ${snippet}`);
  }
  assert.ok(finalReviewRoute.includes("approve_final_submission_package"));
  assert.ok(finalReviewRoute.includes("approved_for_submission"));
  assert.ok(studioPanels.includes("批准最终提交包"));
});

test("package writer separates internal, review, and external outputs", () => {
  const source = readText("src/lib/package.ts");
  const portfolioRenderer = readText("src/lib/portfolioRenderer.ts");

  for (const snippet of [
    "internal-notes",
    "user-review",
    "external-submission",
    "runApplicationQualityChecks",
    "renderPortfolioPackage",
    "sanitizeExternalText",
    "requiresUserFinalApproval"
  ]) {
    assert.ok(source.includes(snippet), `package writer missing ${snippet}`);
  }
  assert.ok(portfolioRenderer.includes("portfolio.html"));
  assert.ok(portfolioRenderer.includes("portfolio.pdf"));
  assert.ok(portfolioRenderer.includes("portfolio-visual-check.json"));
});

test("quality modules block external leakage and generic AI language", () => {
  const sanitizer = readText("src/lib/outputSanitizer.ts");
  const language = readText("src/lib/languageReviewCheck.ts");
  const portfolio = readText("src/lib/portfolioQualityCheck.ts");

  for (const forbidden of ["generated by AI", "internal note", "placeholder", "No Instagram", "TBD", "unknown"]) {
    assert.ok(sanitizer.includes(forbidden), `sanitizer missing ${forbidden}`);
  }
  for (const cliche of ["explores the relationship", "liminal", "poetic resonance"]) {
    assert.ok(language.includes(cliche), `language checker missing ${cliche}`);
  }
  assert.ok(portfolio.includes("No existing portfolio source was found"));
  assert.ok(portfolio.includes("web/design research references"));
});

test("test and mock runs are isolated from real application records", () => {
  const projectAutomation = readText("src/lib/projectAutomation.ts");
  const packageWriter = readText("src/lib/package.ts");
  const opportunityPages = readText("src/lib/opportunityPages.ts");
  const opportunitySearch = readText("src/lib/opportunitySearch.ts");
  const policy = readText("docs/test_run_policy.md");

  assert.ok(projectAutomation.includes("ARTIST_STUDIO_RUN_MODE"));
  assert.ok(projectAutomation.includes("if (runMode === \"real\")"));
  assert.ok(projectAutomation.includes("runMode === \"real\" ? createApplication"));
  assert.ok(projectAutomation.includes("discoverOpportunityCandidates"));
  assert.ok(packageWriter.includes("generated\", `${options.runMode}-runs`"));
  assert.ok(opportunityPages.includes("persist: runMode === \"real\"") || projectAutomation.includes("{ persist: runMode === \"real\" }"));
  assert.ok(opportunitySearch.includes("if (runMode === \"real\")"));
  assert.ok(policy.includes("generated/test-runs/"));
  assert.ok(policy.includes("must not create real application rows"));
});

test("project automation includes global opportunity discovery", () => {
  const opportunitySearch = readText("src/lib/opportunitySearch.ts");
  const automationDocs = readText("docs/automation.md");

  for (const snippet of [
    "ArtConnect",
    "TransArtists",
    "ResArtis",
    "open call",
    "residency",
    "grant",
    "ARTIST_STUDIO_DISCOVERY_SOURCE_URLS"
  ]) {
    assert.ok(opportunitySearch.includes(snippet) || automationDocs.includes(snippet), `discovery support missing ${snippet}`);
  }
});

test("README documents Chinese review and submission boundaries", () => {
  const readme = readText("README.md");

  assert.ok(readme.includes("用户只审核第一节点"));
  assert.ok(readme.includes("用户只审核第二节点"));
  assert.ok(readme.includes("internal-notes/"));
  assert.ok(readme.includes("external-submission/"));
});
